// /tmp/bonsai-en-translations.ts
// Generated by translation agent on 2026-05-26.
// Note: tree-database translations are NOT included here — the existing DE+EN fields in trees.ts are kept as-is for the EN locale.

// Full privacy page body as a single HTML string. Will be spliced into a
// pre-built Astro template that provides Header/Footer/BaseLayout wrapping.
// Include the <header><h1>+date</h1></header> block plus all <section> blocks.
// Use the same class names as the DE source. Reference SITE values via
// Astro template syntax: {SITE.legal.legalEntity}, {SITE.address.street}, etc.
// (Don't translate those reference expressions — leave them as Astro expressions.)
export const EN_PRIVACY = `
<header>
  <h1 class="font-display text-4xl sm:text-5xl text-text italic">Privacy policy</h1>
  <p class="mt-2 text-text-muted">Last updated: May 26, 2026</p>
</header>

<section class="space-y-3">
  <h2 class="font-display text-2xl text-text">1. Data controller</h2>
  <p>The data controller under the DSGVO (the EU's General Data Protection Regulation, commonly called GDPR in English) is:</p>
  <p>
    {SITE.legal.legalEntity}<br />
    {SITE.address.street}, {SITE.address.postalCode} {SITE.address.city}<br />
    Email: <a href={\`mailto:\${SITE.legal.dataControllerEmail}\`} class="text-accent-deep underline">{SITE.legal.dataControllerEmail}</a><br />
    Phone: {SITE.legal.dataControllerPhone}
  </p>
</section>

<section class="space-y-3">
  <h2 class="font-display text-2xl text-text">2. Collection and storage of personal data</h2>
  <p>When you visit this website, general technical information is automatically collected in server log files. This includes details such as the browser you use, your operating system, and the time of your visit. We process this information because it is technically necessary to display the pages you request correctly.</p>
  <p>The legal basis is Art. 6 Abs. 1 lit. f DSGVO (legitimate interest in delivering the site free of technical errors).</p>
</section>

<section class="space-y-3">
  <h2 class="font-display text-2xl text-text">3. Newsletter</h2>
  <p>This demo site processes <strong>no data</strong> when you submit the newsletter form. The form is a non-functional mockup. In a production environment we would use a double opt-in process with a confirmation email, and dispatch the newsletter through a GDPR-compliant provider (for example Brevo or Mailjet, with servers in the EU).</p>
</section>

<section class="space-y-3">
  <h2 class="font-display text-2xl text-text">4. Cookies and tracking</h2>
  <p>We use strictly necessary cookies (to remember your cookie banner choice). Analytics cookies and third-party scripts are loaded only after you give explicit consent through the cookie banner. You can withdraw your consent at any time by clearing the cookies in your browser settings.</p>
</section>

<section class="space-y-3">
  <h2 class="font-display text-2xl text-text">5. Embedded third-party services</h2>
  <ul class="list-disc list-inside space-y-2 text-text-muted">
    {SITE.legal.processors.map((p) => (
      <li><strong class="text-text">{p.name}</strong> — {p.purpose} (location: {p.location})</li>
    ))}
  </ul>
  <p class="text-sm pt-2">We have data processing agreements in place with the processors listed above under Art. 28 DSGVO.</p>
</section>

<section class="space-y-3">
  <h2 class="font-display text-2xl text-text">6. Retention periods</h2>
  <p>We keep personal data only as long as it is needed for the relevant purpose, or as long as statutory retention periods require:</p>
  <ul class="list-disc list-inside space-y-1 text-text-muted">
    <li>Server log files: 7–14 days, then automatic deletion</li>
    <li>Cookie preferences (stored locally in your browser): up to 180 days, or until you delete them</li>
    <li>Email correspondence: until your request is fully resolved; statutory retention rules under the German Commercial Code (HGB) and Tax Code (AO) may require longer storage (up to 10 years for commercially relevant records)</li>
  </ul>
</section>

<section class="space-y-3">
  <h2 class="font-display text-2xl text-text">7. Data security</h2>
  <p>This site uses TLS encryption (HTTPS) for all data transmission. We apply the following technical safeguards:</p>
  <ul class="list-disc list-inside space-y-1 text-text-muted">
    <li>Strict-Transport-Security (HSTS) with preload</li>
    <li>Content-Security-Policy to prevent cross-site scripting</li>
    <li>X-Frame-Options and X-Content-Type-Options to mitigate clickjacking and MIME sniffing</li>
    <li>Access to administrative areas only via multi-factor authentication</li>
  </ul>
  <p>Despite these measures, fully secure data transmission over the internet cannot be guaranteed.</p>
</section>

<section class="space-y-3">
  <h2 class="font-display text-2xl text-text">8. Your rights</h2>
  <p>You have the following rights:</p>
  <ul class="list-disc list-inside space-y-1 text-text-muted">
    <li>Right of access (Art. 15 DSGVO)</li>
    <li>Right to rectification (Art. 16 DSGVO)</li>
    <li>Right to erasure (Art. 17 DSGVO)</li>
    <li>Right to restriction of processing (Art. 18 DSGVO)</li>
    <li>Right to data portability (Art. 20 DSGVO)</li>
    <li>Right to object (Art. 21 DSGVO)</li>
    <li>Right to lodge a complaint with a supervisory authority (Art. 77 DSGVO)</li>
  </ul>
  <p class="pt-2">To exercise your rights, please contact: <a href={\`mailto:\${SITE.legal.dataControllerEmail}\`} class="text-accent-deep underline">{SITE.legal.dataControllerEmail}</a></p>
</section>

<section class="space-y-3 text-text-muted text-sm">
  <h2 class="font-display text-xl text-text">9. Supervisory authority</h2>
  <p>Our competent supervisory authority is the Berliner Beauftragte für Datenschutz und Informationsfreiheit (Berlin Commissioner for Data Protection and Freedom of Information), Friedrichstr. 219, 10969 Berlin.</p>
</section>
`;

export const EN_IMPRINT = `
<h1 class="font-display text-4xl sm:text-5xl text-text italic">Legal notice</h1>
<p class="mt-2 text-text-muted">Information required under § 5 TMG (German law)</p>

<section class="mt-10 space-y-2">
  <h2 class="font-display text-2xl text-text">Provider</h2>
  <p>{SITE.legal.legalEntity}</p>
  <p>{SITE.address.street}</p>
  <p>{SITE.address.postalCode} {SITE.address.city}</p>
  <p>Germany</p>
</section>

<section class="mt-8 space-y-2">
  <h2 class="font-display text-2xl text-text">Represented by</h2>
  <p>{SITE.legal.legalRepresentatives}</p>
</section>

<section class="mt-8 space-y-2">
  <h2 class="font-display text-2xl text-text">Contact</h2>
  <p>Phone: <a href={\`tel:\${SITE.phone}\`} class="text-accent-deep underline">{SITE.phoneDisplay}</a></p>
  <p>Email: <a href={\`mailto:\${SITE.email}\`} class="text-accent-deep underline">{SITE.email}</a></p>
</section>

<section class="mt-8 space-y-2">
  <h2 class="font-display text-2xl text-text">VAT identification number</h2>
  <p>VAT identification number under § 27a UStG (German VAT Act): {SITE.legal.taxId}</p>
</section>

<section class="mt-8 space-y-2">
  <h2 class="font-display text-2xl text-text">Responsible for content under § 18 Abs. 2 MStV</h2>
  <p>{SITE.legal.legalRepresentatives}</p>
  <p>{SITE.address.street}, {SITE.address.postalCode} {SITE.address.city}</p>
</section>

<section class="mt-8 space-y-3 text-text-muted">
  <h2 class="font-display text-2xl text-text">Dispute resolution</h2>
  <p>
    The European Commission provides an online dispute resolution (ODR) platform: <a href="https://ec.europa.eu/consumers/odr" class="text-accent-deep underline" target="_blank" rel="noopener noreferrer">https://ec.europa.eu/consumers/odr</a>.
  </p>
  <p>You can find our email address above in this legal notice.</p>
  <p>We are neither willing nor obligated to participate in dispute resolution proceedings before a consumer arbitration board.</p>
</section>

<section class="mt-8 space-y-3 text-text-muted text-sm">
  <h2 class="font-display text-xl text-text">Disclaimer</h2>
  <p>The contents of this demo site were created for demonstration purposes. Despite careful editing, we accept no liability for the accuracy, completeness, or timeliness of the information provided. The botanical care notes are based on established bonsai practice, but do not replace individual expert advice.</p>
</section>
`;
