// /tmp/bonsai-es-translations.ts
// Generated by translation agent on 2026-05-26.
//
// Castilian (es-ES) cultural adaptations of the Kodama Bonsai tree database +
// privacy + imprint pages. Tone: contemplative, sober, slightly literary.
// Form of address: tú throughout. Season names only (no months). Botanical Latin
// names and Japanese bonsai vocabulary kept untranslated; akadama / pumice / lava
// kept as international bonsai terminology.

export const ES_TREES: Record<
  string,
  {
    popularName: string;
    introduction: string;
    care: {
      sun: string;
      soil: string;
      watering: string;
      fertilizing: string;
      temperature: string;
      pruning: string;
    };
    styles: string[];
    techniques: Array<{ name: string; period: string; description: string }>;
    propagation: { period: string; postCare: string };
    photos: string[];
  }
> = {
  'ficus-retusa': {
    popularName: 'Ficus ginseng',
    introduction:
      'Un bonsái de interior resistente, de follaje lustroso y verde oscuro, con vistosas raíces aéreas. Es muy querido por quienes empiezan porque perdona los descuidos y crece deprisa. Sus raíces carnosas, a veces marcadamente engrosadas, le han valido el sobrenombre de "ginseng".',
    care: {
      sun: 'Luz indirecta intensa; tolera bien algunas horas de sol directo por la mañana. En verano, al exterior en un lugar de semisombra.',
      soil: 'Akadama 60 % + pumice 20 % + lava 20 %, con buen drenaje.',
      watering:
        'Riega cuando la superficie del sustrato empiece a secarse. Soporta mejor una sequía breve que el encharcamiento.',
      fertilizing:
        'Cada dos semanas de primavera a otoño con abono líquido orgánico; en invierno reduce a cada 4–6 semanas.',
      temperature: '18–25 °C todo el año, nunca por debajo de 15 °C; sensible a las heladas.',
      pruning:
        'Despunta los brotes a 2 hojas cuando tengan 6–8; admite una poda fuerte en primavera.',
    },
    styles: [
      'Estilo vertical informal — curvas suaves del tronco, muy frecuente en Ficus.',
      'Estilo banyan, con raíces aéreas marcadas que con el tiempo se convierten en troncos secundarios.',
      'Estilo *ne-agari* — raíces expuestas, característico del Ficus ginseng por sus raíces carnosas.',
    ],
    techniques: [
      {
        name: 'Alambrado',
        period: 'Todo el año, idealmente de finales de primavera al verano',
        description:
          'Emplea alambre de aluminio de 1–4 mm. La corteza es sensible a la presión: revísalo con regularidad y retíralo a las 6–8 semanas, antes de que se marque.',
      },
      {
        name: 'Trasplante',
        period: 'En primavera, con temperaturas por encima de 18 °C',
        description:
          'Reduce el cepellón en un tercio y replanta en sustrato fresco. Se recupera con rapidez.',
      },
      {
        name: 'Defoliación',
        period: 'Principios de verano',
        description:
          'Corta todas las hojas dejando los peciolos. Vuelve a brotar con hojas más pequeñas y afina la ramificación.',
      },
    ],
    propagation: {
      period: 'De primavera a verano',
      postCare:
        'Mantén los esquejes en semisombra, con sustrato uniformemente húmedo y alta humedad ambiental. Enraízan en 4–8 semanas. El acodo aéreo también funciona muy bien.',
    },
    photos: [
      'Ficus ginseng con raíces carnosas',
      'Follaje de Ficus retusa',
      'Bonsái de Ficus en estilo banyan',
    ],
  },
  'ulmus-parvifolia': {
    popularName: 'Olmo chino',
    introduction:
      'Una de las especies más versátiles para bonsái: ramificación fina, hojas pequeñas y una corteza atractiva que se exfolia. En Europa se vende a menudo como bonsái de interior, pero a largo plazo prospera mucho mejor al aire libre. Muy adaptable y tolera bien la poda.',
    care: {
      sun: 'A pleno sol en el exterior; en interior, una ventana luminosa con varias horas de luz directa.',
      soil: 'Akadama 50 % + pumice 25 % + lava 25 %, con buen drenaje.',
      watering:
        'Riega con regularidad en cuanto el sustrato empiece a secarse: a los olmos les gusta la humedad, pero nunca el encharcamiento.',
      fertilizing:
        'Cada dos semanas durante el periodo de crecimiento (de primavera a otoño) con abono líquido orgánico o equilibrado.',
      temperature:
        'En el exterior resiste hasta unos −10 °C con protección radicular; las procedencias chinas necesitan una invernada más resguardada.',
      pruning:
        'Despunta los brotes a 2 hojas cuando tengan 4–6. Poda estructural a finales de invierno, antes del desborre.',
    },
    styles: [
      'Estilo vertical informal — la forma más habitual del olmo chino.',
      'Estilo escoba — copa simétrica y semiesférica, idónea para la ramificación fina del olmo.',
      'Estilo multitronco surgido de una sola base radicular.',
    ],
    techniques: [
      {
        name: 'Alambrado',
        period: 'A finales de otoño e invierno, sin hojas',
        description: 'Alambre de aluminio; la corteza joven es delicada. Revisa a los 3–6 meses.',
      },
      {
        name: 'Trasplante',
        period: 'En primavera, cuando las yemas se hinchan',
        description: 'Acorta las raíces en un tercio. Tolera reducciones radiculares notables.',
      },
      {
        name: 'Defoliación',
        period: 'Principios de verano',
        description:
          'La defoliación total o parcial favorece hojas más pequeñas y una ramificación más fina.',
      },
    ],
    propagation: {
      period: 'Esquejes semileñosos a principios de verano',
      postCare:
        'Semisombra, sustrato húmedo y alta humedad ambiental. Enraízan en 6–10 semanas. También es viable la siembra en primavera.',
    },
    photos: [
      'Olmo chino como bonsái',
      'Hojas de Ulmus parvifolia',
      'Detalle del tronco del olmo chino',
    ],
  },
  'carmona-retusa': {
    popularName: 'Té de Fukien',
    introduction:
      'Un bonsái de interior de hoja pequeña y lustrosa, con delicadas flores blancas casi todo el año, seguidas de pequeñas bayas rojas o negras. Pese a venderse a menudo como árbol para principiantes, es en realidad exigente: reacciona con sensibilidad a los cambios de ubicación, a las corrientes de aire y a un riego irregular.',
    care: {
      sun: 'Muy luminoso, con varias horas de sol directo (ventana sur o este). En verano, al exterior en una posición resguardada.',
      soil: 'Akadama 60 % + pumice 20 % + lava 20 %, ligeramente ácido.',
      watering:
        'Mantén el sustrato uniformemente húmedo, pero nunca encharcado. Prefiere agua baja en cal (agua de lluvia).',
      fertilizing: 'Cada dos semanas de primavera a otoño; en invierno, reducido a una vez al mes.',
      temperature: '18–24 °C todo el año, nunca por debajo de 15 °C; sensible a las heladas.',
      pruning: 'Despunta los brotes a 2 hojas cuando tengan 6–8. Poda más fuerte en primavera.',
    },
    styles: [
      'Estilo vertical informal — el más habitual en el comercio.',
      'Estilo inclinado, con un marcado desvío del tronco.',
      'Estilo cascada — encaja con las ramas florales colgantes de la especie.',
    ],
    techniques: [
      {
        name: 'Alambrado',
        period: 'De primavera a verano, durante el crecimiento activo',
        description:
          'Alambre de aluminio de 1–3 mm. La madera es quebradiza: dobla con cuidado, preferiblemente en varias etapas.',
      },
      {
        name: 'Trasplante',
        period: 'En primavera, con temperaturas por encima de 18 °C',
        description:
          'Poda radicular conservadora (como máximo un cuarto). La Carmona es sensible a una reducción radicular fuerte.',
      },
    ],
    propagation: {
      period: 'Esquejes semileñosos a principios de verano',
      postCare:
        'Calor de fondo de 22–25 °C, alta humedad y semisombra. Enraízan en 6–10 semanas; a menudo es complicado.',
    },
    photos: [
      'Té de Fukien con flores blancas',
      'Detalle de un bonsái de Carmona',
      'Tronco del té de Fukien',
    ],
  },
  'portulacaria-afra': {
    popularName: 'Arbusto elefante / jade enano',
    introduction:
      'Un bonsái suculento de interior extraordinariamente fácil de cuidar, con hojas pequeñas y carnosas y corteza pardo-rojiza. Perdona la sequía, así que resulta ideal tanto para quien empieza como para quien viaja a menudo. Crece sorprendentemente rápido y se modela con facilidad.',
    care: {
      sun: 'Muy luminoso, con sol directo durante todo el año: ventana sur u oeste; al exterior en verano.',
      soil: 'Muy drenante: pumice 50 % + akadama 30 % + lava 20 %, o sustrato para suculentas.',
      watering:
        'Con parquedad: riega solo cuando el sustrato esté completamente seco. En invierno, mantén casi en seco.',
      fertilizing:
        'Una vez al mes de primavera a otoño con abono líquido a media concentración; en invierno suspende el abonado.',
      temperature: '15–30 °C, nunca por debajo de 10 °C; sensible a las heladas.',
      pruning:
        'En cualquier momento: acorta los brotes a la longitud deseada y deja que las heridas cicatricen.',
    },
    styles: [
      'Estilo vertical informal — sigue el porte natural.',
      'Estilo cascada — los brotes blandos lo hacen especialmente adecuado.',
      'Estilo multitronco — se obtiene con facilidad a partir de varios esquejes.',
    ],
    techniques: [
      {
        name: 'Alambrado',
        period: 'Todo el año, idealmente de finales de primavera al verano',
        description:
          'Los brotes jóvenes lignifican deprisa. Atención: son frágiles, así que dobla en varios pequeños pasos.',
      },
      {
        name: 'Trasplante',
        period: 'De primavera a principios de verano',
        description:
          'Antes de plantar, deja secar las raíces 1–2 días y espera una semana antes de volver a regar.',
      },
      {
        name: '*Clip-and-grow*',
        period: 'Periodo de crecimiento',
        description:
          'Más práctico que alambrar: podar con regularidad y dejar que los nuevos brotes marquen la dirección.',
      },
    ],
    propagation: {
      period: 'Todo el año, idealmente de primavera a verano',
      postCare:
        'Deja que los esquejes cicatricen durante 1–3 días y luego clávalos en sustrato seco. Riega ligeramente solo al cabo de 1–2 semanas. Enraízan en 2–4 semanas.',
    },
    photos: ['Bonsái de Portulacaria afra', 'Follaje suculento', 'Tronco del arbusto elefante'],
  },
  'crassula-ovata': {
    popularName: 'Árbol de jade',
    introduction:
      'Un bonsái suculento clásico, de hojas gruesas y lustrosas y un tronco característicamente abultado. Extremadamente parco, ideal para principiantes y para quienes cuidan con olvido. Frente a la Portulacaria su masa foliar es más basta — menos delicada, pero muy robusta.',
    care: {
      sun: 'Mucho sol directo, ventana sur u oeste. En verano, al exterior en un lugar soleado.',
      soil: 'Muy drenante: pumice 50 % + akadama 30 % + lava 20 %, o sustrato para cactáceas.',
      watering:
        'Con mucha parquedad: riega solo cuando el sustrato esté del todo seco. En invierno, mantén casi seco.',
      fertilizing:
        'Una vez al mes de primavera a otoño con abono para suculentas a media concentración; suspende en invierno.',
      temperature: '15–28 °C, nunca por debajo de 8 °C; sensible a las heladas.',
      pruning: 'En cualquier momento: poda los brotes y deja cicatrizar las heridas grandes.',
    },
    styles: [
      'Estilo vertical informal — sigue el porte natural.',
      'Estilo multitronco: la Crassula tiende por naturaleza a emitir varios troncos.',
      'Estilo *bunjin* o literato — tronco esbelto y retorcido con follaje escaso.',
    ],
    techniques: [
      {
        name: 'Trasplante',
        period: 'De primavera a principios de verano, con tiempo cálido',
        description:
          'Deja secar las raíces 2–3 días antes de plantar y mantén el sustrato seco durante 7–10 días.',
      },
      {
        name: '*Clip-and-grow*',
        period: 'Periodo de crecimiento',
        description:
          'El alambrado apenas es viable: la forma se construye exclusivamente mediante poda.',
      },
    ],
    propagation: {
      period: 'De primavera a verano',
      postCare:
        'Deja cicatrizar los esquejes 2–5 días y clávalos en sustrato seco para suculentas. Enraízan con mucha facilidad, a menudo en 3–5 semanas.',
    },
    photos: ['Bonsái de Crassula ovata', 'Hojas del árbol de jade', 'Tronco del árbol de jade'],
  },
  'schefflera-arboricola': {
    popularName: 'Cheflera enana',
    introduction:
      'Un bonsái tropical de interior muy resistente, con llamativas hojas palmadas y propensión a formar raíces aéreas espectaculares. Soporta condiciones de poca luz mejor que la mayoría de los bonsáis de interior. Se diseña a menudo en el estilo "Hawaiian Umbrella", con columnas de raíces aéreas.',
    care: {
      sun: 'De brillante a semisombra; bastan unas horas de luz indirecta. Evita el sol fuerte del mediodía.',
      soil: 'Akadama 50 % + pumice 30 % + lava 20 %, con cierta retención de humedad.',
      watering:
        'Mantén el sustrato uniformemente húmedo. La humedad ambiental alta favorece la formación de raíces aéreas.',
      fertilizing: 'Cada dos semanas de primavera a otoño; una vez al mes en invierno.',
      temperature: '18–25 °C todo el año, nunca por debajo de 12 °C; sensible a las heladas.',
      pruning: 'Acorta los brotes con regularidad a 1–2 hojas. Tolera bien la poda fuerte.',
    },
    styles: [
      'Estilo banyan — el clásico "Hawaiian Umbrella" con raíces aéreas.',
      'Estilo *sekijoju*, raíz sobre roca — las raíces envuelven una piedra.',
      'Estilo vertical informal.',
    ],
    techniques: [
      {
        name: 'Alambrado',
        period: 'Todo el año',
        description:
          'La madera es muy blanda: alambra con cuidado y retira el alambre pronto (4–6 semanas). A menudo conviene más el *clip-and-grow*.',
      },
      {
        name: 'Trasplante',
        period: 'De primavera a principios de verano',
        description: 'Reduce las raíces en un tercio. La Schefflera se recupera deprisa.',
      },
      {
        name: 'Fomentar raíces aéreas',
        period: 'En el periodo de crecimiento, con humedad alta',
        description:
          'Envuelve el tronco con plástico o sphagnum húmedo: las raíces aéreas aparecen en 4–8 semanas.',
      },
    ],
    propagation: {
      period: 'De primavera a verano',
      postCare: 'Semisombra, alta humedad y calor de fondo de 22–25 °C. Enraízan en 4–8 semanas.',
    },
    photos: [
      'Bonsái de Schefflera arboricola',
      'Hojas de la cheflera enana',
      'Hawaiian Umbrella con raíces aéreas',
    ],
  },
  'serissa-foetida': {
    popularName: 'Rosa de las nieves / árbol de las mil estrellas',
    introduction:
      'Un bonsái de interior delicado, cubierto de innumerables flores pequeñas, blancas o rosas, de primavera a otoño. Pese a su aspecto encantador es notoriamente caprichoso: deja caer las hojas al menor cambio. Un "bonsái diva" reservado a manos experimentadas.',
    care: {
      sun: 'Luminoso, con varias horas de sol directo por la mañana; al exterior en verano en un lugar resguardado.',
      soil: 'Akadama 60 % + pumice 20 % + lava 20 %, ligeramente ácido.',
      watering:
        'Mantén uniformemente húmedo: ni que se seque ni que se encharque. Prefiere agua baja en cal.',
      fertilizing:
        'Cada dos semanas de primavera a otoño con abono líquido orgánico; en invierno, reducido a una vez al mes.',
      temperature: '15–22 °C, nunca por debajo de 10 °C; sensible a las heladas.',
      pruning: 'Tras la floración, despunta los brotes a 2 hojas. Poda más fuerte en primavera.',
    },
    styles: [
      'Estilo vertical informal — el más habitual.',
      'Estilo *netsuranari*, raíz conectada — varios troncos surgidos de una sola raíz.',
      'Estilo inclinado.',
    ],
    techniques: [
      {
        name: 'Alambrado',
        period: 'De primavera a verano',
        description:
          'Alambre de aluminio de 1–2 mm. Ramas muy finas y quebradizas: dobla con cuidado.',
      },
      {
        name: 'Trasplante',
        period: 'En primavera',
        description: 'Poda radicular conservadora (como máximo un cuarto). La Serissa es sensible.',
      },
    ],
    propagation: {
      period: 'Esquejes semileñosos a principios de verano',
      postCare: 'Semisombra, humedad ambiental alta y calor de fondo. Enraízan en 6–10 semanas.',
    },
    photos: [
      'Rosa de las nieves en flor',
      'Detalle de un bonsái de Serissa',
      'Árbol de las mil estrellas',
    ],
  },
  'sageretia-theezans': {
    popularName: 'Ciruelo dulce chino',
    introduction:
      'Un atractivo bonsái de interior con hojas pequeñas y lustrosas y una corteza visiblemente moteada que se exfolia. Da pequeñas flores cremosas y bayas violeta azulado. Es sensible al aire seco de la calefacción y necesita una humedad ambiental alta.',
    care: {
      sun: 'Luz indirecta brillante; en verano, al exterior en semisombra.',
      soil: 'Akadama 60 % + pumice 20 % + lava 20 %.',
      watering:
        'Mantén el sustrato uniformemente húmedo: no tolera secarse. Es importante una humedad ambiental superior al 50 %.',
      fertilizing: 'Cada dos semanas de primavera a otoño; una vez al mes en invierno.',
      temperature: '15–22 °C, nunca por debajo de 12 °C; sensible a las heladas.',
      pruning: 'Despunta los brotes a 2 hojas cuando tengan 6–8. Admite poda regular.',
    },
    styles: [
      'Estilo vertical informal — el más habitual.',
      'Estilo escoba — encaja con la ramificación fina.',
      'Estilo multitronco.',
    ],
    techniques: [
      {
        name: 'Alambrado',
        period: 'De primavera a verano',
        description:
          'Alambre de aluminio de 1–3 mm. La corteza es sensible a la presión: revísalo con regularidad.',
      },
      {
        name: 'Trasplante',
        period: 'En primavera',
        description:
          'Acorta las raíces en un tercio. Trasplanta con temperaturas cálidas (por encima de 18 °C).',
      },
    ],
    propagation: {
      period: 'A principios de verano',
      postCare: 'Semisombra, alta humedad y calor de fondo de 22–25 °C. Enraízan en 6–10 semanas.',
    },
    photos: [
      'Bonsái de Sageretia theezans',
      'Corteza del ciruelo dulce chino',
      'Chinese Sweet Plum',
    ],
  },
  'chloroleucon-tortum': {
    popularName: 'Árbol de la lluvia brasileño',
    introduction:
      'Un bonsái tropical exótico procedente de la Mata Atlántica brasileña, conocido por sus ramas retorcidas en espiral y sus hojas finamente pinnadas, que se cierran al caer la noche o al tocarlas. Forma racimos planos de flores blancas y fragantes. Exigente en cuidados, pero visualmente extraordinario.',
    care: {
      sun: 'Muy luminoso, con varias horas de sol directo. En verano, al exterior en un lugar soleado.',
      soil: 'Akadama 50 % + pumice 30 % + lava 20 %, con buen drenaje.',
      watering:
        'Mantén el sustrato uniformemente húmedo, con humedad ambiental alta. La sequía provoca caída de hoja.',
      fertilizing: 'Cada dos semanas de primavera a otoño; en invierno, reducido a una vez al mes.',
      temperature: '20–28 °C, nunca por debajo de 12 °C; muy sensible a las heladas.',
      pruning: 'Tras la lignificación, recorta los brotes a 2–3 pares de hojas.',
    },
    styles: [
      'Estilo vertical informal, con tronco naturalmente retorcido.',
      'Estilo *bunjin* o literato — encaja con la silueta elegante en espiral de las ramas.',
      'Estilo inclinado.',
    ],
    techniques: [
      {
        name: 'Alambrado',
        period: 'De primavera a principios de verano',
        description:
          'Alambra con cuidado: la madera es dura pero frágil. La forma sigue muchas veces la espiral natural.',
      },
      {
        name: 'Trasplante',
        period: 'A finales de primavera, con tiempo cálido',
        description:
          'Poda radicular moderada (como máximo un tercio). Tras el trasplante, mantén el árbol cálido y húmedo.',
      },
    ],
    propagation: {
      period: 'En primavera',
      postCare:
        'Remoja la semilla durante 24 horas en agua tibia. Germina a 25–28 °C en 1–3 semanas. Los esquejes suelen ser poco fiables.',
    },
    photos: ['Árbol de la lluvia brasileño', 'Hojas pinnadas', 'Tronco en espiral'],
  },
  'bougainvillea-glabra': {
    popularName: 'Buganvilla',
    introduction:
      'Un bonsái tropical de floración generosa, con brácteas espectaculares —a menudo en tonos púrpura y rosa— que envuelven las flores verdaderas, mucho más discretas. Lignifica deprisa y desarrolla troncos característicamente nudosos. Necesita mucho sol y un periodo seco para florecer con abundancia.',
    care: {
      sun: 'A pleno sol, tanto como sea posible. En verano, salir al exterior es indispensable.',
      soil: 'Akadama 50 % + pumice 30 % + lava 20 %, con buen drenaje.',
      watering:
        'Riega con generosidad en la fase de crecimiento dejando que el sustrato se seque ligeramente entre riegos. Antes de la floración, mantén deliberadamente seco para inducirla.',
      fertilizing:
        'Cada dos semanas de primavera a otoño; en verano, con abono rico en potasio para favorecer la floración.',
      temperature: '18–30 °C, en invierno como mínimo 10 °C; sensible a las heladas.',
      pruning: 'Poda después de cada floración: las nuevas flores aparecen sobre madera nueva.',
    },
    styles: [
      'Estilo vertical informal.',
      'Estilo cascada — los brotes florales colgantes resultan especialmente vistosos.',
      'Estilo raíz sobre roca — raíces vigorosas que abrazan piedras.',
    ],
    techniques: [
      {
        name: 'Alambrado',
        period: 'En verano, durante el crecimiento activo',
        description:
          'La madera es dura y frágil: alambra los brotes jóvenes y modela las ramas viejas con tirantes. Cuidado con las espinas.',
      },
      {
        name: 'Trasplante',
        period: 'A finales de primavera, con tiempo cálido',
        description:
          'La buganvilla es sensible a la manipulación de las raíces: retira como mucho un cuarto.',
      },
    ],
    propagation: {
      period: 'Esquejes semileñosos en verano',
      postCare:
        'Calor de fondo de 25 °C, alta humedad. El enraizamiento puede llevar 2–3 meses, con éxito moderado. El acodo aéreo suele ser más fiable.',
    },
    photos: ['Bonsái de buganvilla en flor', 'Brácteas de la buganvilla', 'Tronco nudoso'],
  },
  'juniperus-chinensis': {
    popularName: 'Junípero chino',
    introduction:
      'El junípero clásico del bonsái, a menudo trabajado con dramáticas zonas de madera muerta (*jin* y *shari*). No perdona los errores en las raíces, pero es enormemente moldeable y longevo: muchos árboles maestros son juníperos. Las variedades más apreciadas son "Itoigawa" y "Kishu", de follaje en escamas especialmente fino.',
    care: {
      sun: 'A pleno sol todo el año: imprescindible para un follaje denso y un crecimiento sano.',
      soil: 'Akadama 40 % + pumice 40 % + lava 20 %, muy drenante.',
      watering:
        'Riega solo cuando la superficie del sustrato empiece a secarse: los juníperos detestan el encharcamiento.',
      fertilizing:
        'Cada dos semanas durante el periodo de crecimiento (de primavera a otoño) con abono orgánico; suspende en invierno.',
      temperature: 'Rústico hasta −15 °C con protección radicular; al exterior todo el año.',
      pruning:
        'Pellizca las puntas de los brotes con los dedos (no con tijera: las heridas se ennegrecen). Poda estructural a finales de verano.',
    },
    styles: [
      'Estilo vertical informal — muy extendido.',
      'Estilo *shari* / *jin* — modelado de madera muerta, con zonas peladas del tronco y puntas de rama secas.',
      'Estilo cascada — encaja con su porte natural sobre cantiles.',
    ],
    techniques: [
      {
        name: 'Alambrado',
        period: 'De otoño a finales de invierno, durante el reposo vegetativo',
        description:
          'Tradicionalmente alambre de cobre para las ramas estructurales y aluminio para las finas. Déjalo varios meses y revísalo con regularidad.',
      },
      {
        name: 'Trasplante',
        period: 'En primavera, antes de la brotación',
        description:
          'Poda radicular conservadora (como máximo un tercio). Conserva la micorriza: deja parte del sustrato viejo.',
      },
      {
        name: 'Crear *jin* / *shari*',
        period: 'De finales de verano a principios de otoño',
        description:
          'Retira la corteza, esculpe la madera con herramientas de *jin* y blanquéala después con polisulfuro de calcio.',
      },
    ],
    propagation: {
      period: 'Esquejes semileñosos a finales de verano',
      postCare:
        'En cajonera o invernáculo, en semisombra y húmedo. El enraizamiento tarda 6–12 meses. El injerto (por ejemplo, "Itoigawa" sobre patrón vigoroso) también es habitual.',
    },
    photos: [
      'Bonsái de junípero chino',
      'Juniperus con *jin* y *shari*',
      'Follaje en escamas del junípero',
    ],
  },
  'juniperus-procumbens-nana': {
    popularName: 'Junípero rastrero japonés',
    introduction:
      'El "mall bonsai" más extendido del mundo: compacto, robusto y económico. A pesar del mal trato que recibe en el comercio, es un bonsái duro y agradecido para quien empieza, siempre que se mantenga al exterior. Su rasgo distintivo es el follaje en forma de aguja, no en escamas.',
    care: {
      sun: 'A pleno sol todo el año. NUNCA lo mantengas de forma permanente en interior.',
      soil: 'Akadama 40 % + pumice 40 % + lava 20 %, muy drenante.',
      watering:
        'Riega solo cuando el sustrato se haya secado ligeramente. Evita el encharcamiento.',
      fertilizing:
        'Cada dos semanas durante el periodo de crecimiento (de primavera a otoño) con abono orgánico.',
      temperature: 'Rústico hasta −10 °C con protección radicular; al exterior todo el año.',
      pruning: 'Pellizca las puntas con los dedos. Poda estructural en otoño.',
    },
    styles: [
      'Estilo cascada — su porte naturalmente caído lo hace idóneo.',
      'Estilo semicascada — muy frecuente.',
      'Estilo vertical informal.',
    ],
    techniques: [
      {
        name: 'Alambrado',
        period: 'De otoño a finales de invierno',
        description:
          'Alambre de aluminio o cobre. Las ramas jóvenes se moldean bien; déjalo varios meses sobre el árbol.',
      },
      {
        name: 'Trasplante',
        period: 'En primavera',
        description: 'Poda radicular conservadora (como máximo un tercio). Conserva la micorriza.',
      },
    ],
    propagation: {
      period: 'A finales de verano',
      postCare: 'Semisombra, sustrato húmedo, invernada en cajonera. Enraízan en 6–12 meses.',
    },
    photos: ['Junípero rastrero japonés', 'Procumbens en cascada', 'Follaje del Nana'],
  },
  'pinus-thunbergii': {
    popularName: 'Pino negro japonés',
    introduction:
      'La reina del bonsái japonés: simbólica, poderosa, con corteza profundamente surcada. Su cuidado es técnicamente exigente: el corte de velas (*mekiri*), la reducción de acículas y el cuidado de la micorriza son obligatorios. No es un pino para principiantes, pero sí la meta última de muchos aficionados al bonsái.',
    care: {
      sun: 'A pleno sol todo el año: cuanto más sol, más cortas las acículas y más compacto el crecimiento.',
      soil: 'Akadama 30 % + pumice 50 % + lava 20 %, muy drenante. La micorriza es imprescindible.',
      watering:
        'Riega solo cuando el sustrato esté claramente seco. Prefiere quedarse del lado seco antes que del húmedo.',
      fertilizing:
        'Abonado fuerte de primavera a principios de verano y a principios de otoño; reducido en pleno verano. Prefiere abonos en *cakes* orgánicos.',
      temperature: 'Rústico hasta −15 °C con protección radicular; al exterior todo el año.',
      pruning:
        'Corte de velas (*mekiri*) entre finales de primavera y principios de verano: cortar todas las velas obliga a un segundo brote con acículas más cortas.',
    },
    styles: [
      'Estilo *chokkan* o vertical formal — símbolo de fuerza y dignidad.',
      'Estilo vertical informal — muy extendido.',
      'Estilo inclinado — como los pinos costeros doblegados por el viento.',
    ],
    techniques: [
      {
        name: 'Alambrado',
        period: 'De finales de otoño al invierno',
        description:
          'Cobre para tronco y ramas principales, aluminio para la ramificación fina. Permanece durante 12+ meses.',
      },
      {
        name: 'Trasplante',
        period: 'En primavera, cuando se hinchan las yemas',
        description:
          'Poda radicular conservadora (como máximo un tercio). Conserva la micorriza obligatoriamente: no desnudes la raíz por completo.',
      },
      {
        name: '*Mekiri* (corte de velas)',
        period: 'Entre finales de primavera y principios de verano',
        description:
          'Corta por completo las velas primaverales para forzar un segundo brote con acículas más cortas. Técnica clásica para reducir la longitud de la acícula.',
      },
      {
        name: 'Pinzado de acículas (*hadagari*)',
        period: 'En otoño',
        description:
          'Retira las acículas viejas y el exceso de las nuevas para que entre luz al interior y se equilibre el vigor.',
      },
    ],
    propagation: {
      period: 'En primavera, tras estratificación en frío',
      postCare:
        'Estratifica la semilla en frío durante 1–2 meses. Siembra en sustrato arenoso; germina en 4–8 semanas. Los esquejes son muy difíciles; el injerto es la norma para variedades selectas.',
    },
    photos: ['Bonsái de pino negro japonés', 'Corteza del pino negro', 'Pares de acículas'],
  },
  'pinus-parviflora': {
    popularName: 'Pino blanco japonés',
    introduction:
      'Más elegante que el pino negro, con acículas verde plateado agrupadas en haces de cinco. Crece de forma naturalmente lenta y compacta — de ahí su popularidad en el mundo del bonsái. A menudo se injerta sobre patrón de pino negro para conseguir un sistema radicular más vigoroso.',
    care: {
      sun: 'A pleno sol todo el año.',
      soil: 'Akadama 30 % + pumice 50 % + lava 20 %, muy drenante.',
      watering:
        'Con parquedad: el pino blanco prefiere condiciones secas y es propenso a la podredumbre radicular.',
      fertilizing:
        'Abonado moderado durante el periodo de crecimiento (de primavera a otoño). Menos que el pino negro, o las acículas crecerán demasiado.',
      temperature: 'Rústico hasta −15 °C con protección radicular; al exterior todo el año.',
      pruning:
        'Nada de *mekiri* como en el pino negro: en su lugar, parte las velas con los dedos en primavera hasta la longitud deseada.',
    },
    styles: [
      'Estilo *chokkan* o vertical formal.',
      'Estilo vertical informal — el más habitual.',
      'Estilo *bunjin* o literato — tronco esbelto con follaje escaso, muy poético.',
    ],
    techniques: [
      {
        name: 'Alambrado',
        period: 'De finales de otoño al invierno',
        description:
          'Preferiblemente alambre de cobre. La madera quiebra antes que la del pino negro: dobla con prudencia.',
      },
      {
        name: 'Trasplante',
        period: 'En primavera',
        description:
          'Poda radicular muy conservadora (como máximo un cuarto). Conserva la micorriza obligatoriamente.',
      },
      {
        name: 'Partido de velas',
        period: 'En primavera, mientras las velas estén blandas',
        description:
          'Parte las velas frescas con los dedos hasta la longitud deseada; NO las retires por completo como en el pino negro.',
      },
    ],
    propagation: {
      period: 'A finales de invierno',
      postCare:
        'Práctica habitual: injerto sobre Pinus thunbergii. La siembra es posible, pero no garantiza la fidelidad varietal; los esquejes son prácticamente imposibles.',
    },
    photos: ['Pino blanco japonés', 'Haces de cinco acículas', 'Pino blanco en estilo literato'],
  },
  'pinus-sylvestris': {
    popularName: 'Pino silvestre',
    introduction:
      'Un pino nativo de Europa, con la característica corteza naranja rojiza en la parte alta del tronco. Cada vez más apreciado en el bonsái porque puede recolectarse como *yamadori* de las montañas. Más rústico y resistente al frío que los pinos japoneses, pero con técnicas de cultivo similares.',
    care: {
      sun: 'A pleno sol todo el año.',
      soil: 'Akadama 30 % + pumice 50 % + lava 20 %, muy drenante.',
      watering: 'Riega solo cuando el sustrato se haya secado. Soporta bien la sequía.',
      fertilizing:
        'Abonado moderado durante el periodo de crecimiento (de primavera a otoño). Reducido en pleno verano.',
      temperature: 'Muy rústico, hasta −25 °C; al exterior todo el año.',
      pruning: 'Parte las velas en primavera; sin *mekiri*. Aclara las acículas viejas en otoño.',
    },
    styles: [
      'Estilo vertical informal — característico del *yamadori*.',
      'Estilo *bunjin* o literato — encaja con el porte natural de los pinos silvestres viejos.',
      'Estilo *shari* / *jin* — muy frecuente sobre material recogido en montaña.',
    ],
    techniques: [
      {
        name: 'Alambrado',
        period: 'De otoño al invierno',
        description:
          'Preferiblemente alambre de cobre. Los brotes jóvenes se moldean bien; déjalo bastante tiempo.',
      },
      {
        name: 'Trasplante',
        period: 'En primavera o a finales de verano',
        description:
          'Poda radicular conservadora (como máximo un tercio). Conserva la micorriza obligatoriamente.',
      },
      {
        name: 'Aclareo de acículas',
        period: 'En otoño',
        description:
          'Arranca las acículas viejas; retira más en las zonas más vigorosas para equilibrar la energía.',
      },
    ],
    propagation: {
      period: 'En primavera',
      postCare:
        'Estratifica la semilla en frío 4–6 semanas antes de sembrar. Germina en 3–6 semanas. La recogida de *yamadori* a finales de invierno es una vía habitual de obtención.',
    },
    photos: ['Bonsái de pino silvestre', 'Corteza anaranjada', '*Yamadori* de Pinus sylvestris'],
  },
  'acer-palmatum': {
    popularName: 'Arce palmado japonés',
    introduction:
      'Uno de los bonsáis más bellos que existen: hojas finas, lobuladas en cinco a siete divisiones, y una espectacular coloración otoñal en rojo, naranja y amarillo. Numerosas variedades ("Deshojo", "Kiyohime", "Arakawa") ofrecen distintas formas y tonalidades de hoja. Sensible al sol del mediodía y al aire seco.',
    care: {
      sun: 'Sol de mañana y sombra por la tarde. En pleno verano, colócalo en semisombra para evitar quemaduras foliares.',
      soil: 'Akadama 60 % + pumice 20 % + lava 20 %, ligeramente ácido.',
      watering:
        'Mantén el sustrato uniformemente húmedo; en verano puede necesitar dos riegos diarios. No tolera la desecación.',
      fertilizing:
        'Cada dos semanas de primavera a principios de verano y a principios de otoño. Pausa en pleno verano.',
      temperature:
        'Rústico hasta −10 °C con protección radicular; en invierno, resguardado del viento y de las heladas fuertes.',
      pruning:
        'Despunta los brotes a 1 par de hojas cuando tengan 2–3 pares. Poda principal a finales de invierno, antes del desborre.',
    },
    styles: [
      'Estilo escoba — clásico del arce, realza la ramificación fina.',
      'Estilo vertical informal.',
      'Estilo *yose-ue* o bosque — varios troncos, espectacular en otoño.',
    ],
    techniques: [
      {
        name: 'Alambrado',
        period:
          'De finales de primavera a principios de verano, con los brotes aún blandos, o en invierno sin hojas',
        description:
          'Alambre de aluminio. La corteza es muy sensible a la presión: retíralo a las 6–8 semanas.',
      },
      {
        name: 'Trasplante',
        period: 'En primavera, cuando se hinchan las yemas',
        description:
          'Reduce las raíces en un tercio. Sella los cortes con pasta cicatrizante para evitar sangrados.',
      },
      {
        name: 'Defoliación',
        period: 'A principios de verano',
        description:
          'La defoliación total favorece hojas más pequeñas y un color otoñal más intenso. No la hagas todos los años.',
      },
    ],
    propagation: {
      period: 'De primavera a principios de verano',
      postCare:
        'El acodo aéreo es muy fiable: enraíza en 8–12 semanas. La siembra en primavera tras estratificación en frío también funciona; las variedades selectas suelen injertarse.',
    },
    photos: [
      'Arce palmado japonés en otoño',
      'Follaje del arce palmado',
      'Bonsái de Acer palmatum',
    ],
  },
  'acer-buergerianum': {
    popularName: 'Arce tridente',
    introduction:
      'Más robusto que el arce palmado y muy apreciado para quien empieza y para el estudio del *nebari*. Sus hojas trilobuladas son inconfundibles y, con los años, la corteza se cuartea y se exfolia formando una textura magnífica. Desarrolla unos arranques de raíz impresionantes — ideales para bosques y composiciones de raíz sobre roca.',
    care: {
      sun: 'A pleno sol o en semisombra. En pleno verano, una sombra ligera.',
      soil: 'Akadama 60 % + pumice 20 % + lava 20 %.',
      watering: 'Mantén el sustrato uniformemente húmedo; con generosidad en verano.',
      fertilizing: 'Cada dos semanas durante el periodo de crecimiento (de primavera a otoño).',
      temperature: 'Rústico hasta −10 °C con protección radicular; al exterior todo el año.',
      pruning:
        'Despunta los brotes a 1 par de hojas cuando tengan 2–3 pares. Soporta una poda fuerte.',
    },
    styles: [
      'Estilo escoba — la elección clásica.',
      'Estilo raíz sobre roca — raíces vigorosas abrazando las piedras.',
      'Estilo *yose-ue* o bosque — muy frecuente.',
    ],
    techniques: [
      {
        name: 'Alambrado',
        period: 'A finales de invierno (sin hojas) o a principios de verano (brotes aún blandos)',
        description:
          'Alambre de aluminio. La corteza es delicada: revísalo con regularidad y retíralo a las 6–8 semanas.',
      },
      {
        name: 'Trasplante',
        period: 'En primavera',
        description:
          'Acorta las raíces en un tercio. Tolera un trato más agresivo que el A. palmatum.',
      },
      {
        name: 'Defoliación',
        period: 'A principios de verano',
        description:
          'La defoliación total favorece una ramificación más fina y hojas más pequeñas.',
      },
    ],
    propagation: {
      period: 'Esquejes semileñosos a principios de verano',
      postCare:
        'Semisombra y sustrato húmedo. Enraízan en 6–8 semanas. La siembra en primavera tras estratificación en frío también funciona.',
    },
    photos: ['Bonsái de arce tridente', 'Corteza del arce tridente', 'Hojas trilobuladas'],
  },
  'larix-kaempferi': {
    popularName: 'Alerce japonés',
    introduction:
      'Una conífera poco común que en otoño se tiñe de amarillo dorado y pierde las acículas. Crece deprisa y ramifica con finura — ideal para composiciones en bosque y para *yamadori* de los Alpes. La brotación primaveral, de un verde tierno luminoso, resulta de una frescura conmovedora.',
    care: {
      sun: 'A pleno sol todo el año.',
      soil: 'Akadama 50 % + pumice 30 % + lava 20 %, ligeramente ácido.',
      watering:
        'Mantén el sustrato uniformemente húmedo: el alerce agradece más agua que otras coníferas.',
      fertilizing:
        'Cada dos semanas durante el periodo de crecimiento (de primavera a otoño); reducido en pleno verano.',
      temperature: 'Muy rústico, hasta −25 °C; al exterior todo el año.',
      pruning: 'Recorta los brotes nuevos en primavera a 2–3 haces de acículas.',
    },
    styles: [
      'Estilo *yose-ue* o bosque — los alercedos son icónicos (por ejemplo, los de Walter Pall).',
      'Estilo vertical informal.',
      'Estilo *bunjin* o literato — encaja con el porte natural en la línea de árboles alpina.',
    ],
    techniques: [
      {
        name: 'Alambrado',
        period: 'En invierno, sin acículas',
        description:
          'Alambre de aluminio o cobre. La corteza es sensible; durante el ascenso primaveral de la savia, protege la corteza en las ramas más gruesas.',
      },
      {
        name: 'Trasplante',
        period: 'En primavera, justo antes del desborre',
        description: 'Acorta las raíces en un tercio. Conserva la micorriza.',
      },
      {
        name: 'Pinzado de acículas',
        period: 'En primavera, durante el desborre',
        description:
          'Recorta con los dedos los brotes jóvenes y blandos a 2–3 haces de acículas: favorece una ramificación compacta.',
      },
    ],
    propagation: {
      period: 'En primavera, tras estratificación en frío',
      postCare:
        'Estratifica en frío 4–6 semanas. Germina en 3–6 semanas. La recogida de *yamadori* en los Alpes a finales de invierno es habitual.',
    },
    photos: [
      'Bonsái de alerce en otoño',
      'Brotación primaveral del Larix',
      '*Yamadori* de alerce japonés',
    ],
  },
  'chamaecyparis-obtusa': {
    popularName: 'Ciprés hinoki',
    introduction:
      'Una conífera japonesa elegante, de follaje en escamas formando abanicos y un porte naturalmente compacto. La variedad "Nana Gracilis" es la más apreciada en bonsái. Los brotes interiores mueren con facilidad si reciben poca luz: el aclareo regular es obligado.',
    care: {
      sun: 'A pleno sol o en semisombra; es esencial que la luz penetre hasta el interior.',
      soil: 'Akadama 50 % + pumice 30 % + lava 20 %, ligeramente ácido.',
      watering: 'Mantén el sustrato uniformemente húmedo; nunca dejes que se seque.',
      fertilizing:
        'Cada dos semanas durante el periodo de crecimiento (de primavera a otoño) con abono orgánico.',
      temperature: 'Rústico hasta −15 °C con protección radicular; al exterior todo el año.',
      pruning:
        'Pellizca con los dedos los brotes en escamas (no los cortes con tijera: las heridas se ennegrecen). Aclara con regularidad.',
    },
    styles: [
      'Estilo *chokkan* o vertical formal — evoca a los hinokis de los templos.',
      'Estilo vertical informal.',
      'Estilo *yose-ue* o bosque — muy expresivo.',
    ],
    techniques: [
      {
        name: 'Alambrado',
        period: 'De finales de verano al otoño',
        description:
          'Alambre de cobre. La madera es relativamente flexible; revísalo con regularidad.',
      },
      {
        name: 'Trasplante',
        period: 'En primavera, antes del desborre',
        description: 'Poda radicular conservadora (como máximo un tercio). Conserva la micorriza.',
      },
      {
        name: 'Aclareo',
        period: 'De finales de verano al otoño',
        description:
          'Retira los brotes interiores y los que se solapan para que la luz entre al interior — previene la muerte de los brotes internos.',
      },
    ],
    propagation: {
      period: 'Esquejes semileñosos a finales de verano',
      postCare:
        'En cajonera, en semisombra y con sustrato húmedo. Enraízan en 6–12 meses. El injerto es habitual para variedades selectas.',
    },
    photos: ['Ciprés hinoki', 'Follaje en escamas del Nana Gracilis', 'Bonsái de Chamaecyparis'],
  },
  'fagus-sylvatica': {
    popularName: 'Haya común',
    introduction:
      'Una caducifolia europea de corteza lisa y gris plateada y hoja marcescente, cobriza, que permanece en el árbol todo el invierno. Muy apreciada para bosques y como ejemplar solitario. De crecimiento lento, pero con el tiempo desarrolla un tronco bellamente surcado y una copa densa.',
    care: {
      sun: 'Semisombra: el haya no tolera el sol fuerte del mediodía, sobre todo en verano.',
      soil: 'Akadama 50 % + pumice 30 % + lava 20 %, ligeramente ácido.',
      watering:
        'Mantén el sustrato uniformemente húmedo; con generosidad en verano, sin dejar que se seque nunca.',
      fertilizing: 'Cada dos semanas de primavera a principios de verano y a principios de otoño.',
      temperature: 'Muy rústica, hasta −20 °C; al exterior todo el año.',
      pruning:
        'Poda principal a finales de invierno, antes del desborre. Solo UNA brotación al año: no admite podas repetidas como el arce.',
    },
    styles: [
      'Estilo *chokkan* o vertical formal — sigue su porte natural.',
      'Estilo *yose-ue* o bosque — los hayedos figuran entre las composiciones de bonsái más bellas.',
      'Estilo vertical informal.',
    ],
    techniques: [
      {
        name: 'Alambrado',
        period: 'De finales de otoño al invierno',
        description:
          'Alambre de aluminio. La corteza es muy sensible: usa cinta protectora, máximo 4–6 semanas.',
      },
      {
        name: 'Trasplante',
        period: 'En primavera, cuando se hinchan las yemas',
        description: 'Acorta las raíces con cautela, en torno a un tercio.',
      },
      {
        name: 'Selección de yemas',
        period: 'A finales de invierno',
        description:
          'Como el haya solo brota una vez al año, retira selectivamente las yemas sobrantes para canalizar la energía hacia los brotes elegidos.',
      },
    ],
    propagation: {
      period:
        'En otoño, inmediatamente tras la maduración del fruto, o en primavera tras estratificación en frío',
      postCare:
        'Estratifica en frío 3 meses. Germina en primavera. Los esquejes son muy difíciles: la recogida de *yamadori* es una alternativa popular.',
    },
    photos: [
      'Haya común como bonsái',
      'Marcescencia invernal del haya',
      'Composición en bosque de Fagus',
    ],
  },
  'chaenomeles-japonica': {
    popularName: 'Membrillero japonés',
    introduction:
      'Un bonsái de floración armado de espinas, con flores rojas, rosas o blancas de tono encendido a principios de primavera, a menudo antes de que aparezcan las hojas. Da pequeños membrillos fragantes. Admite una poda fuerte y florece con generosidad, pero necesita un reposo invernal frío para que la floración sea abundante.',
    care: {
      sun: 'A pleno sol todo el año.',
      soil: 'Akadama 50 % + pumice 30 % + lava 20 %.',
      watering: 'Mantén el sustrato uniformemente húmedo; con generosidad en verano.',
      fertilizing:
        'Cada dos semanas durante el periodo de crecimiento (de primavera a otoño); en verano, con abono rico en potasio para inducir yemas florales.',
      temperature:
        'Rústico hasta −20 °C; al exterior todo el año, necesita un periodo frío para que se forme la floración.',
      pruning:
        'Poda inmediatamente después de la floración: las yemas florales se forman sobre madera vieja.',
    },
    styles: [
      'Estilo vertical informal.',
      'Estilo multitronco — porte natural.',
      'Estilo semicascada.',
    ],
    techniques: [
      {
        name: 'Alambrado',
        period: 'De finales de otoño al invierno',
        description:
          'Alambre de aluminio. Cuidado con las espinas. No alambres demasiado prieto: la corteza es sensible.',
      },
      {
        name: 'Trasplante',
        period: 'En primavera, justo tras la floración, o antes del desborre',
        description: 'Acorta las raíces en un tercio.',
      },
      {
        name: 'Poda posfloración',
        period: 'Inmediatamente tras la floración',
        description:
          'Recorta los brotes marchitos a 2–3 yemas. En verano, sin podas fuertes: arrastrarían las yemas florales del año siguiente.',
      },
    ],
    propagation: {
      period: 'Esquejes semileñosos en verano',
      postCare:
        'Semisombra, sustrato húmedo, invernada en cajonera. Enraízan en 8–12 semanas. También los hijuelos de raíz son viables.',
    },
    photos: [
      'Membrillero japonés con flores rojas',
      'Bonsái de Chaenomeles',
      'Fruto del membrillero',
    ],
  },
  'wisteria-sinensis': {
    popularName: 'Glicinia china',
    introduction:
      'Un bonsái de floración espectacular, con racimos colgantes de flores violetas o blancas a finales de primavera. Muy vigorosa y sedienta: en verano necesita cantidades enormes de agua. Los troncos viejos desarrollan una corteza extraordinariamente surcada y un grosor nudoso impresionante.',
    care: {
      sun: 'A pleno sol todo el año — imprescindible para la floración.',
      soil: 'Akadama 50 % + pumice 30 % + lava 20 %, con cierta retención de humedad.',
      watering:
        'Muy sedienta: en verano puede necesitar dos riegos diarios. Durante la floración, conviene colocar la maceta temporalmente sobre una bandeja con agua.',
      fertilizing:
        'Cada dos semanas durante el periodo de crecimiento (de primavera a otoño); en verano, con abono rico en fósforo y potasio.',
      temperature: 'Rústica hasta −20 °C; al exterior todo el año.',
      pruning:
        'En verano, recorta los largos sarmientos a 4–6 yemas: favorece la formación de yemas florales. Poda estructural en invierno.',
    },
    styles: [
      'Estilo cascada — encaja con el porte naturalmente colgante de la floración.',
      'Estilo semicascada — el más habitual.',
      'Estilo vertical informal con racimos colgantes.',
    ],
    techniques: [
      {
        name: 'Alambrado',
        period: 'En primavera, tras la floración',
        description:
          'Cobre para las ramas viejas, aluminio para los sarmientos jóvenes. La glicinia crece a una velocidad extrema: revisa el alambre con regularidad.',
      },
      {
        name: 'Trasplante',
        period: 'En primavera, antes del desborre, o justo tras la floración',
        description:
          'Tolera bien una poda radicular agresiva (hasta la mitad): la glicinia produce una masa radicular enorme.',
      },
      {
        name: 'Poda estival para floración',
        period: 'En pleno verano',
        description:
          'Recorta los sarmientos estivales largos a 4–6 yemas: empuja al árbol a generar yemas florales en lugar de masa foliar.',
      },
    ],
    propagation: {
      period: 'De primavera a principios de verano',
      postCare:
        'El acodo aéreo da muy buen resultado; enraíza en 6–12 semanas. Desde semilla tarda 7–15 años en florecer por primera vez: se prefieren plantas injertadas.',
    },
    photos: ['Bonsái de glicinia en flor', 'Racimos de glicinia', 'Tronco nudoso de glicinia'],
  },
  'prunus-mume': {
    popularName: 'Albaricoquero japonés / Ume',
    introduction:
      'Símbolo del Año Nuevo japonés y primer anuncio de la primavera: sus flores fragantes —rosas, blancas o rojas— aparecen a finales de invierno, a menudo todavía bajo la nieve. Los árboles viejos desarrollan troncos característicamente nudosos, de gran dramatismo. Una de las especies de bonsái de mayor carga espiritual en Japón.',
    care: {
      sun: 'A pleno sol todo el año — imprescindible para una floración generosa.',
      soil: 'Akadama 50 % + pumice 30 % + lava 20 %.',
      watering: 'Mantén el sustrato uniformemente húmedo; con generosidad en verano.',
      fertilizing:
        'Cada dos semanas durante el periodo de crecimiento (de primavera a otoño); abonado fuerte tras la floración, con énfasis en el potasio en verano.',
      temperature:
        'Rústico hasta −15 °C con protección radicular; necesita un periodo frío para que se forme la floración.',
      pruning:
        'Poda con energía inmediatamente después de la floración: las yemas florales se forman sobre la madera del año anterior.',
    },
    styles: [
      'Estilo *bunjin* o literato — encaja con el porte nudoso y elegante del Ume viejo.',
      'Estilo vertical informal.',
      'Estilo *shari* — zonas de madera muerta, símbolo de la supervivencia de los árboles antiguos.',
    ],
    techniques: [
      {
        name: 'Alambrado',
        period: 'De finales de otoño al invierno, sin hojas',
        description:
          'La madera es dura y frágil: dobla con cuidado y en varias etapas. Usa cinta protectora.',
      },
      {
        name: 'Trasplante',
        period: 'Inmediatamente tras la floración',
        description: 'Acorta las raíces en un tercio. Sella los cortes con pasta cicatrizante.',
      },
      {
        name: 'Poda posfloración',
        period: 'Inmediatamente tras la floración',
        description:
          'Recorta con fuerza los brotes marchitos a 2–3 yemas para favorecer las yemas florales del año siguiente.',
      },
    ],
    propagation: {
      period: 'De primavera a principios de verano',
      postCare:
        'El acodo aéreo es muy fiable. Los esquejes son posibles pero delicados. Las variedades se suelen injertar.',
    },
    photos: [
      'Flores de Ume a finales de invierno',
      'Bonsái de Prunus mume',
      'Tronco nudoso de Ume',
    ],
  },
  'olea-europaea': {
    popularName: 'Olivo',
    introduction:
      'Una de las plantas cultivadas más antiguas del mundo, con follaje plateado verdoso y, en los ejemplares viejos, un tronco naturalmente nudoso y a menudo hueco. Muy apreciado como *yamadori* recogido en España, Italia y Grecia. Resiste la sequía estupendamente, pero en Berlín no es plenamente rústico: necesita pasar el invierno en un refugio frío y libre de heladas.',
    care: {
      sun: 'A pleno sol todo el año, tanto como sea posible.',
      soil: 'Akadama 40 % + pumice 40 % + lava 20 %, muy drenante.',
      watering:
        'Con parquedad: riega solo cuando el sustrato se haya secado claramente. Soporta bien la sequía.',
      fertilizing:
        'Cada dos semanas durante el periodo de crecimiento (de primavera a otoño) con abono orgánico.',
      temperature:
        'Soporta puntualmente hasta unos −5 °C; en Berlín, inverna libre de heladas (0–10 °C) y con luz.',
      pruning:
        'Tras la lignificación, recorta los brotes a 2–3 pares de hojas. Admite una poda muy fuerte, incluso sobre madera vieja.',
    },
    styles: [
      'Estilo vertical informal, con tronco nudoso.',
      'Estilo *shari* — los troncos naturalmente huecos de los olivos viejos son idóneos.',
      'Estilo *bunjin* o literato — encaja con la silueta elegante.',
    ],
    techniques: [
      {
        name: 'Alambrado',
        period: 'De finales de primavera al verano, durante el crecimiento activo',
        description:
          'La madera es dura, pero sorprendentemente flexible. Cobre para las ramas principales, aluminio para los brotes finos.',
      },
      {
        name: 'Trasplante',
        period: 'A finales de primavera, con temperaturas estables por encima de 15 °C',
        description:
          'Acorta las raíces en un tercio. El olivo se recupera deprisa si se mantiene cálido y soleado.',
      },
      {
        name: 'Defoliación',
        period: 'A principios de verano',
        description:
          'La defoliación total favorece hojas más pequeñas y una ramificación más fina; es viable cada 2–3 años.',
      },
    ],
    propagation: {
      period: 'De primavera a verano',
      postCare:
        'Los esquejes semileñosos enraízan en 8–12 semanas en condiciones de semisombra y humedad. La recogida de *yamadori* en el Mediterráneo es una vía de obtención habitual.',
    },
    photos: ['Olivo como bonsái', 'Follaje plateado verdoso del olivo', 'Tronco hueco del olivo'],
  },
};

// Full privacy page body, spliced into the pre-built Astro template. Uses the
// same class names as the DE source. References SITE values via Astro
// expressions, left unchanged.
export const ES_PRIVACY = `
<header>
  <h1 class="font-display text-4xl sm:text-5xl text-text italic">Política de privacidad</h1>
  <p class="mt-2 text-text-muted">Actualizada: 26 de mayo de 2026</p>
</header>

<section class="space-y-3">
  <h2 class="font-display text-2xl text-text">1. Responsable del tratamiento</h2>
  <p>El responsable del tratamiento en el sentido del Reglamento General de Protección de Datos (RGPD / DSGVO) es:</p>
  <p>
    {SITE.legal.legalEntity}<br />
    {SITE.address.street}, {SITE.address.postalCode} {SITE.address.city}<br />
    Correo electrónico: <a href={\`mailto:\${SITE.legal.dataControllerEmail}\`} class="text-accent-deep underline">{SITE.legal.dataControllerEmail}</a><br />
    Teléfono: {SITE.legal.dataControllerPhone}
  </p>
</section>

<section class="space-y-3">
  <h2 class="font-display text-2xl text-text">2. Recogida y almacenamiento de datos personales</h2>
  <p>Cuando visitas este sitio web se registran automáticamente datos de carácter general (archivos de registro del servidor). Son de naturaleza técnica: por ejemplo, el navegador utilizado, el sistema operativo o el momento de la visita. Esta información se procesa por necesidad técnica para mostrarte correctamente la página solicitada.</p>
  <p>La base jurídica es el art. 6.1.f) del RGPD (interés legítimo en una presentación técnicamente impecable).</p>
</section>

<section class="space-y-3">
  <h2 class="font-display text-2xl text-text">3. Boletín</h2>
  <p>Este sitio de demostración <strong>no procesa ningún dato</strong> al darse de alta en el boletín. El formulario es una maqueta no funcional. En un entorno real utilizaríamos el procedimiento de doble opt-in con correo de confirmación y gestionaríamos el envío mediante un proveedor conforme con el RGPD (por ejemplo, Brevo o Mailjet, con servidores en la UE).</p>
</section>

<section class="space-y-3">
  <h2 class="font-display text-2xl text-text">4. Cookies y seguimiento</h2>
  <p>Empleamos cookies técnicamente necesarias (estado del banner de cookies). Las cookies analíticas y los scripts externos solo se cargan tras tu consentimiento expreso a través del banner. Puedes retirar tu consentimiento en cualquier momento eliminando las cookies en la configuración del navegador.</p>
</section>

<section class="space-y-3">
  <h2 class="font-display text-2xl text-text">5. Servicios de terceros integrados</h2>
  <ul class="list-disc list-inside space-y-2 text-text-muted">
    {SITE.legal.processors.map((p) => (
      <li><strong class="text-text">{p.name}</strong> — {p.purpose} (Ubicación: {p.location})</li>
    ))}
  </ul>
  <p class="text-sm pt-2">Con los encargados del tratamiento mencionados existen contratos de encargo de tratamiento conforme al art. 28 del RGPD.</p>
</section>

<section class="space-y-3">
  <h2 class="font-display text-2xl text-text">6. Plazos de conservación</h2>
  <p>Conservamos los datos personales solo durante el tiempo necesario para los fines respectivos o el que exijan los plazos legales de conservación:</p>
  <ul class="list-disc list-inside space-y-1 text-text-muted">
    <li>Archivos de registro del servidor: 7–14 días; supresión automática posterior.</li>
    <li>Preferencias de cookies (guardadas localmente en el navegador): hasta 180 días o hasta que las borres.</li>
    <li>Correspondencia por correo electrónico: hasta la resolución completa de tu solicitud; los plazos legales de conservación según la legislación mercantil y fiscal alemana (HGB / AO) pueden exigir una conservación más larga (máximo 10 años para operaciones con relevancia mercantil).</li>
  </ul>
</section>

<section class="space-y-3">
  <h2 class="font-display text-2xl text-text">7. Seguridad de los datos</h2>
  <p>Este sitio web utiliza cifrado TLS (HTTPS) para toda la transmisión de datos. Aplicamos las siguientes medidas técnicas de protección:</p>
  <ul class="list-disc list-inside space-y-1 text-text-muted">
    <li>Strict-Transport-Security (HSTS) con preload.</li>
    <li>Content-Security-Policy para impedir ataques de Cross-Site-Scripting.</li>
    <li>X-Frame-Options y X-Content-Type-Options frente al clickjacking y al MIME-sniffing.</li>
    <li>Acceso a las áreas de administración exclusivamente mediante autenticación multifactor.</li>
  </ul>
  <p>A pesar de estas medidas, no puede garantizarse una transmisión de datos completamente segura a través de internet.</p>
</section>

<section class="space-y-3">
  <h2 class="font-display text-2xl text-text">8. Tus derechos</h2>
  <p>Te asisten los siguientes derechos:</p>
  <ul class="list-disc list-inside space-y-1 text-text-muted">
    <li>Derecho de acceso (art. 15 RGPD).</li>
    <li>Derecho de rectificación (art. 16 RGPD).</li>
    <li>Derecho de supresión (art. 17 RGPD).</li>
    <li>Derecho a la limitación del tratamiento (art. 18 RGPD).</li>
    <li>Derecho a la portabilidad de los datos (art. 20 RGPD).</li>
    <li>Derecho de oposición (art. 21 RGPD).</li>
    <li>Derecho a presentar una reclamación ante la autoridad de control (art. 77 RGPD).</li>
  </ul>
  <p class="pt-2">Para ejercer tus derechos, escríbenos a: <a href={\`mailto:\${SITE.legal.dataControllerEmail}\`} class="text-accent-deep underline">{SITE.legal.dataControllerEmail}</a></p>
</section>

<section class="space-y-3 text-text-muted text-sm">
  <h2 class="font-display text-xl text-text">9. Autoridad de control</h2>
  <p>La autoridad de control competente para nosotros es la Berliner Beauftragte für Datenschutz und Informationsfreiheit (Comisionada de Berlín para la Protección de Datos y la Libertad de Información), Friedrichstr. 219, 10969 Berlín.</p>
</section>
`;

// Full imprint page body, spliced into the pre-built Astro template. German
// legal citations (§ 5 TMG, § 27a USt-IdNr, § 18 MStV) remain identified by
// their German references; a brief Spanish gloss flags them as German law.
export const ES_IMPRINT = `
<h1 class="font-display text-4xl sm:text-5xl text-text italic">Aviso legal</h1>
<p class="mt-2 text-text-muted">Información obligatoria conforme al § 5 de la TMG (legislación alemana).</p>

<section class="mt-10 space-y-2">
  <h2 class="font-display text-2xl text-text">Proveedor</h2>
  <p>{SITE.legal.legalEntity}</p>
  <p>{SITE.address.street}</p>
  <p>{SITE.address.postalCode} {SITE.address.city}</p>
  <p>Alemania</p>
</section>

<section class="mt-8 space-y-2">
  <h2 class="font-display text-2xl text-text">Representación legal</h2>
  <p>{SITE.legal.legalRepresentatives}</p>
</section>

<section class="mt-8 space-y-2">
  <h2 class="font-display text-2xl text-text">Contacto</h2>
  <p>Teléfono: <a href={\`tel:\${SITE.phone}\`} class="text-accent-deep underline">{SITE.phoneDisplay}</a></p>
  <p>Correo electrónico: <a href={\`mailto:\${SITE.email}\`} class="text-accent-deep underline">{SITE.email}</a></p>
</section>

<section class="mt-8 space-y-2">
  <h2 class="font-display text-2xl text-text">Número de identificación a efectos del IVA</h2>
  <p>Número de identificación a efectos del IVA conforme al § 27a de la Ley alemana del IVA (Umsatzsteuergesetz): {SITE.legal.taxId}</p>
</section>

<section class="mt-8 space-y-2">
  <h2 class="font-display text-2xl text-text">Responsable de los contenidos conforme al § 18.2 de la MStV (legislación alemana)</h2>
  <p>{SITE.legal.legalRepresentatives}</p>
  <p>{SITE.address.street}, {SITE.address.postalCode} {SITE.address.city}</p>
</section>

<section class="mt-8 space-y-3 text-text-muted">
  <h2 class="font-display text-2xl text-text">Resolución de litigios</h2>
  <p>
    La Comisión Europea pone a disposición una plataforma para la resolución de litigios en línea (ODR): <a href="https://ec.europa.eu/consumers/odr" class="text-accent-deep underline" target="_blank" rel="noopener noreferrer">https://ec.europa.eu/consumers/odr</a>.
  </p>
  <p>Encontrarás nuestra dirección de correo electrónico más arriba en este aviso legal.</p>
  <p>No estamos dispuestos ni obligados a participar en procedimientos de resolución de litigios ante un organismo de arbitraje de consumo.</p>
</section>

<section class="mt-8 space-y-3 text-text-muted text-sm">
  <h2 class="font-display text-xl text-text">Exención de responsabilidad</h2>
  <p>Los contenidos de este sitio de demostración se han elaborado con fines demostrativos. A pesar del cuidado puesto en su elaboración, no se asume responsabilidad alguna por la exactitud, integridad o actualidad de la información facilitada. Las indicaciones botánicas de cultivo se basan en la práctica habitual del bonsái, pero no sustituyen un asesoramiento técnico individualizado.</p>
</section>
`;
