// /tmp/bonsai-pt-br-translations.ts
// Generated by translation agent on 2026-05-26.

export const PTBR_TREES: Record<
  string,
  {
    popularName: string;
    introduction: string;
    care: {
      sun: string;
      soil: string;
      watering: string;
      fertilizing: string;
      temperature: string;
      pruning: string;
    };
    styles: string[];
    techniques: Array<{ name: string; period: string; description: string }>;
    propagation: { period: string; postCare: string };
    photos: string[];
  }
> = {
  'ficus-retusa': {
    popularName: 'Ficus ginseng',
    introduction:
      'Um bonsai de interior robusto, de folhagem verde-escura brilhante e raízes aéreas marcantes. Especialmente apreciado por iniciantes — perdoa erros de cultivo e cresce com rapidez. As raízes carnudas, às vezes muito engrossadas, lhe valeram o apelido de "ginseng".',
    care: {
      sun: 'Luz clara indireta; algumas horas de sol direto pela manhã são bem-vindas. No verão, leve para fora em local de meia-sombra.',
      soil: 'Akadama 60% + pumice 20% + lava 20%, com drenagem livre.',
      watering:
        'Regue assim que a superfície do substrato começar a secar. Tolera períodos curtos de seca melhor do que encharcamento.',
      fertilizing:
        'A cada duas semanas, da primavera ao outono, com adubo orgânico líquido; no inverno, reduzido para cada 4 a 6 semanas.',
      temperature: '18–25 °C o ano todo; não abaixo de 15 °C, sensível a geada.',
      pruning:
        'Pince os brotos quando tiverem 6 a 8 folhas, deixando duas; tolera podas drásticas na primavera.',
    },
    styles: [
      'Estilo *moyogi* — vertical informal, com curvas suaves no tronco, muito comum em Ficus.',
      'Estilo *banyan*, com raízes aéreas pronunciadas que se transformam em troncos secundários.',
      'Estilo *ne-agari* — raízes expostas, típico do Ficus ginseng com seus corpos radiculares carnudos.',
    ],
    techniques: [
      {
        name: 'Aramação',
        period: 'Possível o ano todo, ideal do final da primavera ao verão',
        description:
          'Use arame de alumínio de 1 a 4 mm. A casca é sensível à pressão — inspecione com regularidade e retire em 6 a 8 semanas, antes que se incruste.',
      },
      {
        name: 'Repotagem',
        period: 'Primavera, com temperatura acima de 18 °C',
        description:
          'Reduza a massa radicular em um terço e replante em substrato fresco. A recuperação é rápida.',
      },
      {
        name: 'Desfolha',
        period: 'Início do verão',
        description:
          'Corte todas as folhas mantendo os pecíolos. O rebrote vem com folhas menores e refina a ramificação.',
      },
    ],
    propagation: {
      period: 'Primavera–verão',
      postCare:
        'Mantenha em meia-sombra, com substrato uniformemente úmido e alta umidade do ar. O enraizamento ocorre em 4 a 8 semanas. A alporquia também funciona muito bem.',
    },
    photos: [
      'Ficus ginseng com raízes carnudas',
      'Folhagem de Ficus retusa',
      'Bonsai de Ficus no estilo banyan',
    ],
  },
  'ulmus-parvifolia': {
    popularName: 'Olmo-chinês',
    introduction:
      'Uma das espécies de bonsai mais versáteis — ramificação fina, folhas pequenas e uma casca atraente que se descama. Muitas vezes vendido na Europa como bonsai de interior, mas a longo prazo prospera bem melhor ao ar livre. Bastante adaptável e tolerante a podas.',
    care: {
      sun: 'Sol pleno ao ar livre; em ambiente interno, em janela bem iluminada com algumas horas de luz direta.',
      soil: 'Akadama 50% + pumice 25% + lava 25%, bem drenado.',
      watering:
        'Regue com regularidade assim que o substrato começa a secar — os olmos gostam de umidade, mas nunca de encharcamento.',
      fertilizing:
        'A cada duas semanas durante o período de crescimento (primavera–outono), com adubo orgânico ou líquido equilibrado.',
      temperature:
        'Ao ar livre, rústico até cerca de −10 °C com proteção das raízes; procedências chinesas pedem inverno mais abrigado.',
      pruning:
        'Pince os brotos quando tiverem 4 a 6 folhas, deixando duas. Poda estrutural no final do inverno, antes da brotação.',
    },
    styles: [
      'Estilo *moyogi* — vertical informal, a forma mais comum para o olmo-chinês.',
      'Estilo *hokidachi* — vassoura, copa simétrica em domo, ideal para a ramificação fina do olmo.',
      'Estilo *kabudachi* — multitroncos a partir de uma única base radicular.',
    ],
    techniques: [
      {
        name: 'Aramação',
        period: 'Final do outono ao inverno, sem folhas',
        description: 'Arame de alumínio; a casca jovem é sensível. Verifique após 3 a 6 meses.',
      },
      {
        name: 'Repotagem',
        period: 'Primavera, quando as gemas incham',
        description: 'Encurte as raízes em um terço. Tolera redução radicular significativa.',
      },
      {
        name: 'Desfolha',
        period: 'Início do verão',
        description: 'Desfolha total ou parcial favorece folhas menores e ramificação mais fina.',
      },
    ],
    propagation: {
      period: 'Estacas semilenhosas no início do verão',
      postCare:
        'Meia-sombra, substrato úmido, alta umidade do ar. Enraizamento em 6 a 10 semanas. A semeadura na primavera também é viável.',
    },
    photos: [
      'Olmo-chinês como bonsai',
      'Folhas de Ulmus parvifolia',
      'Detalhe do tronco de olmo-chinês',
    ],
  },
  'carmona-retusa': {
    popularName: 'Chá-de-Fukien',
    introduction:
      'Um bonsai de interior de folhas pequenas e brilhantes, frequentemente vendido como árvore para iniciantes, embora exija cuidados refinados. Florece em pequenas flores brancas durante praticamente todo o ano, seguidas de frutos vermelhos ou pretos. Sensível a mudanças de local, correntes de ar e oscilações na rega.',
    care: {
      sun: 'Muito clara, com algumas horas de sol direto (janela sul ou leste). No verão, ao ar livre em local abrigado.',
      soil: 'Akadama 60% + pumice 20% + lava 20%, levemente ácido.',
      watering:
        'Mantenha o substrato uniformemente úmido, sem nunca encharcar. Prefira água com baixo teor de cálcio (água da chuva).',
      fertilizing:
        'A cada duas semanas, da primavera ao outono; no inverno, reduzido para uma vez por mês.',
      temperature: '18–24 °C o ano todo; não abaixo de 15 °C, sensível a geada.',
      pruning:
        'Pince os brotos quando tiverem 6 a 8 folhas, deixando duas. Poda mais firme na primavera.',
    },
    styles: [
      'Estilo *moyogi* — vertical informal, o mais comum no comércio.',
      'Estilo *shakan* — inclinado, com pronunciada inclinação do tronco.',
      'Estilo *kengai* — cascata, harmoniza com os ramos floridos pendentes da espécie.',
    ],
    techniques: [
      {
        name: 'Aramação',
        period: 'Primavera–verão, durante o crescimento ativo',
        description:
          'Arame de alumínio de 1 a 3 mm. A madeira é quebradiça — dobre com cuidado e em várias etapas.',
      },
      {
        name: 'Repotagem',
        period: 'Primavera, com temperatura acima de 18 °C',
        description:
          'Poda de raízes conservadora (no máximo um quarto). A Carmona é sensível a reduções radiculares severas.',
      },
    ],
    propagation: {
      period: 'Estacas semilenhosas no início do verão',
      postCare:
        'Calor de base entre 22 e 25 °C, alta umidade do ar, meia-sombra. Enraizamento em 6 a 10 semanas — frequentemente difícil.',
    },
    photos: [
      'Chá-de-Fukien com flores brancas',
      'Detalhe de bonsai de Carmona',
      'Tronco de Chá-de-Fukien',
    ],
  },
  'portulacaria-afra': {
    popularName: 'Árvore-da-jade-anã / planta-do-elefante',
    introduction:
      'Um bonsai de interior suculento e extremamente fácil de cultivar, de folhas pequenas e carnudas e casca castanho-avermelhada. Perdoa a seca e por isso é ideal para iniciantes e para quem viaja muito. Cresce surpreendentemente rápido e responde bem à modelagem.',
    care: {
      sun: 'Muito clara, com sol direto o ano todo — janela sul ou oeste; no verão, ao ar livre.',
      soil: 'Muito drenante: pumice 50% + akadama 30% + lava 20%, ou substrato para suculentas.',
      watering:
        'Com parcimônia — só regue quando o substrato estiver completamente seco. No inverno, mantenha quase seca.',
      fertilizing:
        'Uma vez por mês, da primavera ao outono, com adubo líquido em meia dose; suspenda no inverno.',
      temperature: '15–30 °C; não abaixo de 10 °C, sensível a geada.',
      pruning:
        'Possível em qualquer época — encurte os brotos no comprimento desejado e deixe os cortes cicatrizarem.',
    },
    styles: [
      'Estilo *moyogi* — vertical informal, condiz com o hábito natural de crescimento.',
      'Estilo *kengai* — cascata, particularmente adequado pela maleabilidade dos brotos.',
      'Estilo *kabudachi* — multitroncos, facilmente obtido a partir de várias estacas.',
    ],
    techniques: [
      {
        name: 'Aramação',
        period: 'O ano todo, ideal do final da primavera ao verão',
        description:
          'Os brotos jovens lignificam rápido. Cuidado: os ramos são quebradiços, então dobre em vários pequenos passos.',
      },
      {
        name: 'Repotagem',
        period: 'Primavera–início do verão',
        description:
          'Deixe as raízes secarem por 1 a 2 dias antes do plantio e espere uma semana para voltar a regar.',
      },
      {
        name: 'Técnica *clip-and-grow*',
        period: 'Período de crescimento',
        description:
          'Muitas vezes preferível à aramação: pode com regularidade e deixe os novos brotos assumirem a direção.',
      },
    ],
    propagation: {
      period: 'O ano todo, ideal na primavera–verão',
      postCare:
        'Deixe as estacas cicatrizarem por 1 a 3 dias, depois insira em substrato seco. Só regue levemente após 1 ou 2 semanas. Enraizamento em 2 a 4 semanas.',
    },
    photos: ['Bonsai de Portulacaria afra', 'Folhagem suculenta', 'Tronco de planta-do-elefante'],
  },
  'crassula-ovata': {
    popularName: 'Árvore-da-jade / árvore-do-dinheiro',
    introduction:
      'Um clássico bonsai suculento de folhas grossas e brilhantes e tronco caracteristicamente engrossado. Extremamente despretensioso, ideal para iniciantes e para cuidadores esquecidos. Comparada à Portulacaria, a folhagem é mais grosseira — menos delicada, mas muito resistente.',
    care: {
      sun: 'Muito sol direto, em janela sul ou oeste. No verão, ao ar livre em local ensolarado.',
      soil: 'Muito drenante: pumice 50% + akadama 30% + lava 20%, ou substrato para cactos.',
      watering:
        'Muito parcamente — só regue quando o substrato estiver totalmente seco. No inverno, mantenha quase seca.',
      fertilizing:
        'Uma vez por mês, da primavera ao outono, com adubo para suculentas em meia dose; suspenda no inverno.',
      temperature: '15–28 °C; não abaixo de 8 °C, sensível a geada.',
      pruning:
        'Possível em qualquer época — encurte os brotos e deixe os cortes maiores cicatrizarem.',
    },
    styles: [
      'Estilo *moyogi* — vertical informal, segue o hábito natural.',
      'Estilo *kabudachi* — multitroncos; a Crassula brota vários troncos por natureza.',
      'Estilo *bunjin* — literato, tronco esguio e retorcido, com folhagem esparsa.',
    ],
    techniques: [
      {
        name: 'Repotagem',
        period: 'Primavera–início do verão, em tempo quente',
        description:
          'Deixe as raízes secarem por 2 a 3 dias antes do plantio e depois mantenha secas por 7 a 10 dias.',
      },
      {
        name: 'Técnica *clip-and-grow*',
        period: 'Período de crescimento',
        description:
          'A aramação dificilmente funciona — a forma é desenvolvida exclusivamente pela poda.',
      },
    ],
    propagation: {
      period: 'Primavera–verão',
      postCare:
        'Deixe as estacas cicatrizarem por 2 a 5 dias, depois insira em substrato seco para suculentas. Enraíza com muita facilidade, geralmente em 3 a 5 semanas.',
    },
    photos: [
      'Bonsai de Crassula ovata',
      'Folhas de árvore-da-jade',
      'Tronco de árvore-do-dinheiro',
    ],
  },
  'schefflera-arboricola': {
    popularName: 'Cheflera-anã',
    introduction:
      'Um bonsai tropical de interior robusto, com folhas palmadas marcantes e propensão a desenvolver raízes aéreas espetaculares. Tolera baixa luminosidade melhor do que a maioria dos bonsais de interior. Frequentemente modelado no estilo "Hawaiian Umbrella", com colunas de raízes aéreas.',
    care: {
      sun: 'De clara a meia-sombra; algumas horas de luz indireta bastam. Evite o sol forte do meio-dia.',
      soil: 'Akadama 50% + pumice 30% + lava 20%, com boa retenção de umidade.',
      watering:
        'Mantenha o substrato uniformemente úmido. Umidade do ar alta favorece a formação de raízes aéreas.',
      fertilizing: 'A cada duas semanas da primavera ao outono; uma vez por mês no inverno.',
      temperature: '18–25 °C o ano todo; não abaixo de 12 °C, sensível a geada.',
      pruning: 'Aparae os brotos regularmente, deixando 1 ou 2 folhas. Tolera podas drásticas.',
    },
    styles: [
      'Estilo *banyan* — o clássico "Hawaiian Umbrella" com raízes aéreas.',
      'Estilo *sekijoju* — raiz-sobre-pedra, raízes envolvendo uma rocha.',
      'Estilo *moyogi* — vertical informal.',
    ],
    techniques: [
      {
        name: 'Aramação',
        period: 'Possível o ano todo',
        description:
          'A madeira é muito mole — arame com cuidado e retire cedo (em 4 a 6 semanas). Muitas vezes a técnica *clip-and-grow* é preferível.',
      },
      {
        name: 'Repotagem',
        period: 'Primavera–início do verão',
        description: 'Reduza as raízes em um terço. A Schefflera recupera-se com rapidez.',
      },
      {
        name: 'Estímulo de raízes aéreas',
        period: 'Período de crescimento, com alta umidade',
        description:
          'Envolva o tronco com saco plástico ou esfagno úmido; raízes aéreas surgem em 4 a 8 semanas.',
      },
    ],
    propagation: {
      period: 'Primavera–verão',
      postCare:
        'Meia-sombra, alta umidade do ar, calor de base entre 22 e 25 °C. Enraizamento em 4 a 8 semanas.',
    },
    photos: [
      'Bonsai de Schefflera arboricola',
      'Folhas de cheflera-anã',
      'Hawaiian Umbrella com raízes aéreas',
    ],
  },
  'serissa-foetida': {
    popularName: 'Serissa / árvore-das-mil-estrelas',
    introduction:
      'Um bonsai de interior delicado, coberto por incontáveis flores pequenas brancas ou rosadas da primavera ao outono. Apesar da aparência graciosa, é famoso por seu temperamento difícil — perde folhas à menor mudança. Uma "diva" do bonsai, reservada a cultivadores experientes.',
    care: {
      sun: 'Clara, com algumas horas de sol direto pela manhã; no verão, ao ar livre em local abrigado.',
      soil: 'Akadama 60% + pumice 20% + lava 20%, levemente ácido.',
      watering:
        'Mantenha uniformemente úmido — nem secar nem encharcar. Prefira água com baixo teor de cálcio.',
      fertilizing:
        'A cada duas semanas da primavera ao outono, com adubo orgânico líquido; uma vez por mês no inverno.',
      temperature: '15–22 °C; não abaixo de 10 °C, sensível a geada.',
      pruning: 'Pince os brotos para duas folhas após a floração. Poda mais firme na primavera.',
    },
    styles: [
      'Estilo *moyogi* — vertical informal, o mais comum.',
      'Estilo *netsuranari* — raízes interligadas, vários troncos a partir de uma única raiz.',
      'Estilo *shakan* — inclinado.',
    ],
    techniques: [
      {
        name: 'Aramação',
        period: 'Primavera–verão',
        description:
          'Arame de alumínio de 1 a 2 mm. Ramos muito finos e quebradiços — dobre com cuidado.',
      },
      {
        name: 'Repotagem',
        period: 'Primavera',
        description: 'Poda de raízes conservadora (no máximo um quarto). A Serissa é sensível.',
      },
    ],
    propagation: {
      period: 'Estacas semilenhosas no início do verão',
      postCare: 'Meia-sombra, alta umidade do ar, calor de base. Enraizamento em 6 a 10 semanas.',
    },
    photos: ['Serissa em floração', 'Detalhe de bonsai de Serissa', 'Árvore-das-mil-estrelas'],
  },
  'sageretia-theezans': {
    popularName: 'Ameixa-doce-chinesa',
    introduction:
      'Um atraente bonsai de interior, com folhas pequenas e brilhantes e uma casca notavelmente mosqueada que se descama. Produz pequenas flores creme e frutinhas azul-violáceas. Sensível ao ar seco da calefação e exige umidade alta.',
    care: {
      sun: 'Clara, luz indireta; no verão, ao ar livre em meia-sombra.',
      soil: 'Akadama 60% + pumice 20% + lava 20%.',
      watering:
        'Mantenha o substrato uniformemente úmido — não tolera ressecamento. Umidade do ar alta (acima de 50%) é importante.',
      fertilizing: 'A cada duas semanas da primavera ao outono; uma vez por mês no inverno.',
      temperature: '15–22 °C; não abaixo de 12 °C, sensível a geada.',
      pruning:
        'Pince os brotos quando tiverem 6 a 8 folhas, deixando duas. Tolera podas regulares.',
    },
    styles: [
      'Estilo *moyogi* — vertical informal, o mais comum.',
      'Estilo *hokidachi* — vassoura, condiz com a ramificação fina.',
      'Estilo *kabudachi* — multitroncos.',
    ],
    techniques: [
      {
        name: 'Aramação',
        period: 'Primavera–verão',
        description:
          'Arame de alumínio de 1 a 3 mm. A casca é sensível à pressão — monitore com frequência.',
      },
      {
        name: 'Repotagem',
        period: 'Primavera',
        description: 'Encurte as raízes em um terço. Replante em tempo quente (acima de 18 °C).',
      },
    ],
    propagation: {
      period: 'Início do verão',
      postCare:
        'Meia-sombra, alta umidade do ar, calor de base entre 22 e 25 °C. Enraizamento em 6 a 10 semanas.',
    },
    photos: [
      'Bonsai de Sageretia theezans',
      'Casca de ameixa-doce-chinesa',
      'Sageretia em detalhe',
    ],
  },
  'chloroleucon-tortum': {
    popularName: 'Chuva-de-ouro-da-mata-atlântica',
    introduction:
      'Um exótico bonsai tropical da Mata Atlântica brasileira, conhecido pelos ramos em espiral e pelas folhas finamente pinadas que se fecham à noite ou ao toque. Produz inflorescências planas, brancas e perfumadas. Exige cuidados atentos, mas é visualmente impressionante.',
    care: {
      sun: 'Muito clara, com algumas horas de sol direto. No verão, ao ar livre em local ensolarado.',
      soil: 'Akadama 50% + pumice 30% + lava 20%, bem drenado.',
      watering:
        'Mantenha o substrato uniformemente úmido, com alta umidade do ar. A seca provoca queda das folhas.',
      fertilizing:
        'A cada duas semanas da primavera ao outono; reduzido para uma vez por mês no inverno.',
      temperature: '20–28 °C; não abaixo de 12 °C, muito sensível a geada.',
      pruning: 'Pode os brotos depois de lignificados, deixando 2 a 3 pares de folhas.',
    },
    styles: [
      'Estilo *moyogi* — vertical informal, com tronco naturalmente retorcido.',
      'Estilo *bunjin* — literato, condiz com o porte elegante e espiralado dos ramos.',
      'Estilo *shakan* — inclinado.',
    ],
    techniques: [
      {
        name: 'Aramação',
        period: 'Primavera–início do verão',
        description:
          'Arame com cuidado — a madeira é dura, mas quebradiça. A forma muitas vezes já segue a espiral natural.',
      },
      {
        name: 'Repotagem',
        period: 'Final da primavera, em tempo quente',
        description:
          'Poda de raízes moderada (no máximo um terço). Após o replantio, mantenha em ambiente quente e úmido.',
      },
    ],
    propagation: {
      period: 'Primavera',
      postCare:
        'Deixe as sementes de molho em água morna por 24 horas. A germinação ocorre entre 25 e 28 °C em 1 a 3 semanas. As estacas costumam ser pouco confiáveis.',
    },
    photos: ['Chuva-de-ouro-da-mata-atlântica', 'Folhas pinadas', 'Tronco em espiral'],
  },
  'bougainvillea-glabra': {
    popularName: 'Primavera / buganvília',
    introduction:
      'Um bonsai tropical de floração exuberante, com brácteas espetaculares — geralmente roxas ou rosadas — que envolvem as discretas flores verdadeiras. Lignifica rápido e desenvolve troncos caracteristicamente retorcidos. Para florescer com fartura, exige muito sol e um período de seca controlada.',
    care: {
      sun: 'Sol pleno — o quanto for possível. Levar para fora no verão é indispensável.',
      soil: 'Akadama 50% + pumice 30% + lava 20%, bem drenado.',
      watering:
        'Generosa durante o crescimento, deixando o substrato secar levemente entre regas. Antes da floração, mantenha de propósito mais seca para induzir botões.',
      fertilizing:
        'A cada duas semanas da primavera ao outono; no verão, adubo rico em potássio para favorecer a floração.',
      temperature: '18–30 °C; no inverno, mínimo de 10 °C, sensível a geada.',
      pruning: 'Pode após cada floração — as novas flores surgem em madeira nova.',
    },
    styles: [
      'Estilo *moyogi* — vertical informal.',
      'Estilo *kengai* — cascata; os ramos floridos pendentes ficam especialmente atraentes.',
      'Estilo *sekijoju* — raiz-sobre-pedra, com raízes vigorosas abraçando rochas.',
    ],
    techniques: [
      {
        name: 'Aramação',
        period: 'Verão, durante o crescimento ativo',
        description:
          'A madeira é dura e quebradiça — arame os brotos jovens e modele os ramos mais velhos com tirantes. Atenção aos espinhos.',
      },
      {
        name: 'Repotagem',
        period: 'Final da primavera, em tempo quente',
        description:
          'A buganvília é sensível ao mexer das raízes — remova no máximo um quarto delas.',
      },
    ],
    propagation: {
      period: 'Estacas semilenhosas no verão',
      postCare:
        'Calor de base de 25 °C, alta umidade do ar. O enraizamento pode levar de 2 a 3 meses, com sucesso moderado. A alporquia costuma ser mais confiável.',
    },
    photos: ['Bonsai de buganvília em floração', 'Brácteas de primavera', 'Tronco retorcido'],
  },
  'juniperus-chinensis': {
    popularName: 'Junípero-chinês',
    introduction:
      'O junípero clássico do bonsai, frequentemente modelado com áreas dramáticas de madeira morta — *jin* e *shari*. Não perdoa erros nas raízes, mas é extraordinariamente moldável e longevo — muitas obras-primas do bonsai são juníperos. Os cultivares Itoigawa e Kishu, de folhagem escamosa especialmente fina, são os mais apreciados.',
    care: {
      sun: 'Sol pleno o ano todo — indispensável para folhagem densa e brotos saudáveis.',
      soil: 'Akadama 40% + pumice 40% + lava 20%, muito drenante.',
      watering:
        'Só regue quando a superfície do substrato começar a secar — os juníperos detestam encharcamento.',
      fertilizing:
        'A cada duas semanas durante o período de crescimento (primavera–outono), com adubo orgânico; suspenda no inverno.',
      temperature: 'Rústico até −15 °C com proteção radicular; ao ar livre o ano todo.',
      pruning:
        'Pince as pontas dos brotos com os dedos (não com tesoura — os cortes ficam marrons). Poda estrutural no final do verão.',
    },
    styles: [
      'Estilo *moyogi* — vertical informal, muito difundido.',
      'Estilo *shari / jin* — modelagem de madeira morta, com seções do tronco descascadas e pontas de ramos mortos.',
      'Estilo *kengai* — cascata, condiz com o porte natural em paredões rochosos.',
    ],
    techniques: [
      {
        name: 'Aramação',
        period: 'Outono ao final do inverno, em dormência',
        description:
          'Arame de cobre tradicionalmente para a estrutura, alumínio para os ramos finos. Mantenha por vários meses e inspecione com regularidade.',
      },
      {
        name: 'Repotagem',
        period: 'Primavera, antes da brotação',
        description:
          'Poda de raízes conservadora (no máximo um terço). Preserve a micorriza — leve um pouco do substrato antigo.',
      },
      {
        name: 'Criação de *jin/shari*',
        period: 'Final do verão ao início do outono',
        description:
          'Descasque a madeira, esculpa com ferramentas próprias para *jin* e, em seguida, branqueie com calda sulfocálcica.',
      },
    ],
    propagation: {
      period: 'Estacas semilenhosas no final do verão',
      postCare:
        'Em estufim frio ou túnel plástico, em meia-sombra, mantidas úmidas. O enraizamento leva de 6 a 12 meses. A enxertia (por exemplo, Itoigawa sobre porta-enxerto robusto) também é comum.',
    },
    photos: [
      'Bonsai de junípero-chinês',
      'Juniperus com jin e shari',
      'Folhagem escamosa de junípero',
    ],
  },
  'juniperus-procumbens-nana': {
    popularName: 'Junípero-rasteiro-japonês',
    introduction:
      'O "bonsai de shopping" mais comum no mundo — compacto, resistente e barato. Apesar do péssimo trato no varejo, é uma árvore tenaz e gratificante para iniciantes, desde que cultivada ao ar livre. Folhagem em forma de agulha, e não escamosa — traço distintivo.',
    care: {
      sun: 'Sol pleno o ano todo — JAMAIS o mantenha permanentemente em ambiente interno.',
      soil: 'Akadama 40% + pumice 40% + lava 20%, muito drenante.',
      watering: 'Só regue quando o substrato estiver levemente seco. Evite encharcamento.',
      fertilizing:
        'A cada duas semanas durante o período de crescimento (primavera–outono), com adubo orgânico.',
      temperature: 'Rústico até −10 °C com proteção radicular; ao ar livre o ano todo.',
      pruning: 'Pince as pontas dos brotos com os dedos. Poda estrutural no outono.',
    },
    styles: [
      'Estilo *kengai* — cascata; o hábito naturalmente pendente o torna ideal.',
      'Estilo *han-kengai* — semicascata, muito comum.',
      'Estilo *moyogi* — vertical informal.',
    ],
    techniques: [
      {
        name: 'Aramação',
        period: 'Outono ao final do inverno',
        description:
          'Arame de alumínio ou cobre. Os ramos jovens se moldam bem; mantenha o arame por vários meses.',
      },
      {
        name: 'Repotagem',
        period: 'Primavera',
        description: 'Poda de raízes conservadora (no máximo um terço). Preserve a micorriza.',
      },
    ],
    propagation: {
      period: 'Final do verão',
      postCare:
        'Meia-sombra, úmido, com inverno passado em estufim frio. Enraizamento em 6 a 12 meses.',
    },
    photos: ['Junípero-rasteiro-japonês', 'Procumbens em cascata', 'Folhagem de Nana'],
  },
  'pinus-thunbergii': {
    popularName: 'Pinheiro-negro-japonês',
    introduction:
      'A rainha dos bonsais japoneses — carregada de simbolismo, vigorosa, de casca profundamente fissurada. Os cuidados são tecnicamente exigentes: o corte das velas (*mekiri*), a redução de acículas e o trato da micorriza são obrigatórios. Não é para iniciantes, mas é o objetivo final de muitos apaixonados pelo bonsai.',
    care: {
      sun: 'Sol pleno o ano todo — quanto mais sol, mais curtas as acículas e mais compactos os brotos.',
      soil: 'Akadama 30% + pumice 50% + lava 20%, muito drenante. Micorriza indispensável.',
      watering:
        'Só regue quando o substrato estiver visivelmente seco. Prefere o lado seco ao úmido.',
      fertilizing:
        'Adubação forte da primavera ao início do verão e no início do outono, reduzida no pleno verão. Preferência por *cakes* orgânicos.',
      temperature: 'Rústico até −15 °C com proteção radicular; ao ar livre o ano todo.',
      pruning:
        'Corte das velas (*mekiri*) no final da primavera ao início do verão — cortam-se todas as velas, e o pinheiro responde com um segundo fluxo de acículas mais curtas.',
    },
    styles: [
      'Estilo *chokkan* — vertical formal, símbolo de força e dignidade.',
      'Estilo *moyogi* — vertical informal, muito difundido.',
      'Estilo *shakan* — inclinado, como pinheiros litorâneos torcidos pelo vento.',
    ],
    techniques: [
      {
        name: 'Aramação',
        period: 'Final do outono ao inverno',
        description:
          'Arame de cobre para tronco e ramos principais, alumínio para a ramificação fina. Permanece por 12 meses ou mais.',
      },
      {
        name: 'Repotagem',
        period: 'Primavera, quando as gemas incham',
        description:
          'Poda de raízes conservadora (no máximo um terço). Preserve a micorriza — não lave totalmente as raízes.',
      },
      {
        name: '*Mekiri* (corte das velas)',
        period: 'Final da primavera ao início do verão',
        description:
          'Corte por completo as velas da primavera, forçando o pinheiro a um segundo fluxo com acículas mais curtas. Técnica clássica de redução de acículas.',
      },
      {
        name: 'Limpeza de acículas (*hadagari*)',
        period: 'Outono',
        description:
          'Remova acículas velhas e o excesso das novas para deixar a luz penetrar e equilibrar o crescimento.',
      },
    ],
    propagation: {
      period: 'Primavera, após estratificação a frio',
      postCare:
        'Estratifique as sementes a frio por 1 a 2 meses. Semeie em substrato arenoso; germinação em 4 a 8 semanas. Estacas muito difíceis — a enxertia é o padrão para cultivares selecionados.',
    },
    photos: ['Bonsai de pinheiro-negro-japonês', 'Casca de pinheiro-negro', 'Acículas em feixe'],
  },
  'pinus-parviflora': {
    popularName: 'Pinheiro-branco-japonês',
    introduction:
      'Mais elegante que o pinheiro-negro, com acículas verde-prateadas em feixes de cinco. Cresce naturalmente devagar e de forma compacta — daí sua popularidade no bonsai. Costuma ser enxertado sobre pinheiro-negro para obter sistemas radiculares mais robustos.',
    care: {
      sun: 'Sol pleno o ano todo.',
      soil: 'Akadama 30% + pumice 50% + lava 20%, muito drenante.',
      watering:
        'Com parcimônia — o pinheiro-branco gosta de condições secas e é suscetível à podridão radicular.',
      fertilizing:
        'Adubação moderada durante o período de crescimento (primavera–outono). Menos que o pinheiro-negro, caso contrário as acículas crescem demais.',
      temperature: 'Rústico até −15 °C com proteção radicular; ao ar livre o ano todo.',
      pruning:
        'Sem *mekiri* como no pinheiro-negro — em vez disso, quebram-se as velas na primavera no comprimento desejado.',
    },
    styles: [
      'Estilo *chokkan* — vertical formal.',
      'Estilo *moyogi* — vertical informal, o mais comum.',
      'Estilo *bunjin* — literato, tronco esguio e folhagem esparsa, muito poético.',
    ],
    techniques: [
      {
        name: 'Aramação',
        period: 'Final do outono ao inverno',
        description:
          'Arame de cobre, preferencialmente. A madeira quebra com mais facilidade que a do pinheiro-negro — dobre com cuidado.',
      },
      {
        name: 'Repotagem',
        period: 'Primavera',
        description:
          'Poda de raízes muito conservadora (no máximo um quarto). Preserve a micorriza obrigatoriamente.',
      },
      {
        name: 'Quebra das velas',
        period: 'Primavera, com as velas ainda macias',
        description:
          'Quebre as velas frescas com os dedos no comprimento desejado, NÃO remova por completo como no pinheiro-negro.',
      },
    ],
    propagation: {
      period: 'Final do inverno',
      postCare:
        'Prática padrão: enxertar sobre Pinus thunbergii. A semeadura é possível, mas a constância varietal é incerta; as estacas, quase impossíveis.',
    },
    photos: [
      'Pinheiro-branco-japonês',
      'Feixes de cinco acículas',
      'Pinheiro-branco em estilo bunjin',
    ],
  },
  'pinus-sylvestris': {
    popularName: 'Pinheiro-silvestre',
    introduction:
      'Um pinheiro nativo da Europa, de casca alaranjada característica na parte superior do tronco. Vem ganhando popularidade no bonsai por ser coletável como *yamadori* nas montanhas. Mais rústico e tolerante ao frio que os pinheiros japoneses, mas o manejo segue técnicas semelhantes.',
    care: {
      sun: 'Sol pleno o ano todo.',
      soil: 'Akadama 30% + pumice 50% + lava 20%, muito drenante.',
      watering: 'Só regue quando o substrato estiver seco. Suporta bem a seca.',
      fertilizing:
        'Adubação moderada durante o período de crescimento (primavera–outono). Mais parca no pleno verão.',
      temperature: 'Muito rústico, até −25 °C; ao ar livre o ano todo.',
      pruning: 'Quebre as velas na primavera, sem *mekiri*. Limpe as acículas velhas no outono.',
    },
    styles: [
      'Estilo *moyogi* — vertical informal, típico do *yamadori*.',
      'Estilo *bunjin* — literato, condiz com o porte natural dos pinheiros-silvestres mais antigos.',
      'Estilo *shari / jin* — modelagem com madeira morta, muito comum em material de *yamadori*.',
    ],
    techniques: [
      {
        name: 'Aramação',
        period: 'Outono ao inverno',
        description:
          'Arame de cobre, preferencialmente. Os brotos jovens dobram bem; mantenha o arame por longos períodos.',
      },
      {
        name: 'Repotagem',
        period: 'Primavera ou final do verão',
        description:
          'Poda de raízes conservadora (no máximo um terço). Preserve a micorriza obrigatoriamente.',
      },
      {
        name: 'Redução de pares de acículas',
        period: 'Outono',
        description:
          'Arranque as acículas velhas e retire mais nas áreas vigorosas para equilibrar a energia.',
      },
    ],
    propagation: {
      period: 'Primavera',
      postCare:
        'Estratifique as sementes a frio por 4 a 6 semanas antes da semeadura. Germinação em 3 a 6 semanas. A coleta de *yamadori* no final do inverno é uma fonte comum.',
    },
    photos: ['Bonsai de pinheiro-silvestre', 'Casca alaranjada', 'Pinus sylvestris yamadori'],
  },
  'acer-palmatum': {
    popularName: 'Bordo-japonês',
    introduction:
      'Um dos bonsais mais belos que existem — folhas finas, de cinco a sete lóbulos, e uma coloração outonal espetacular em tons de vermelho, laranja e amarelo. Muitos cultivares ("Deshojo", "Kiyohime", "Arakawa") oferecem diferentes formas e cores de folha. Sensível ao sol do meio-dia e ao ar seco.',
    care: {
      sun: 'Sol da manhã e sombra à tarde — em pleno verão, em meia-sombra para evitar queima das folhas.',
      soil: 'Akadama 60% + pumice 20% + lava 20%, levemente ácido.',
      watering:
        'Mantenha o substrato uniformemente úmido; no verão, pode ser necessário regar duas vezes ao dia. Não tolera ressecamento.',
      fertilizing:
        'A cada duas semanas da primavera ao início do verão e no início do outono. Pausa no pleno verão.',
      temperature:
        'Rústico até −10 °C com proteção radicular; no inverno, abrigue do vento e da geada intensa.',
      pruning:
        'Pince os brotos para um par de folhas quando tiverem 2 a 3 pares. Poda principal no final do inverno, antes da brotação.',
    },
    styles: [
      'Estilo *hokidachi* — vassoura, clássico para o bordo, realça a ramificação fina.',
      'Estilo *moyogi* — vertical informal.',
      'Estilo *yose-ue* — floresta, vários troncos, espetacular no outono.',
    ],
    techniques: [
      {
        name: 'Aramação',
        period:
          'Final da primavera ao início do verão, com brotos macios, ou no inverno sem folhas',
        description:
          'Arame de alumínio. A casca é muito sensível à pressão — retire em 6 a 8 semanas.',
      },
      {
        name: 'Repotagem',
        period: 'Primavera, quando as gemas incham',
        description:
          'Reduza as raízes em um terço. Sele os cortes com pasta cicatrizante para evitar sangramento.',
      },
      {
        name: 'Desfolha',
        period: 'Início do verão',
        description:
          'A desfolha total favorece folhas menores e cores outonais mais intensas. Não faça todo ano.',
      },
    ],
    propagation: {
      period: 'Primavera–início do verão',
      postCare:
        'A alporquia é muito confiável — enraizamento em 8 a 12 semanas. A semeadura na primavera, após estratificação a frio; cultivares geralmente vão enxertados.',
    },
    photos: ['Bordo-japonês no outono', 'Folhas de bordo', 'Bonsai de Acer palmatum'],
  },
  'acer-buergerianum': {
    popularName: 'Bordo-tridente',
    introduction:
      'Mais robusto que o bordo-japonês e muito popular entre iniciantes e para estudos de *nebari* (raízes superficiais). Apresenta folhas trilobadas características e, com a idade, uma casca lindamente rachada e descamante. Desenvolve bases radiculares impressionantes — ideal para estilos em floresta e raiz-sobre-pedra.',
    care: {
      sun: 'Do sol pleno à meia-sombra. Sombra leve no pleno verão.',
      soil: 'Akadama 60% + pumice 20% + lava 20%.',
      watering: 'Mantenha o substrato uniformemente úmido, com fartura no verão.',
      fertilizing: 'A cada duas semanas durante o período de crescimento (primavera–outono).',
      temperature: 'Rústico até −10 °C com proteção radicular; ao ar livre o ano todo.',
      pruning:
        'Pince os brotos para um par de folhas quando tiverem 2 a 3 pares. Tolera podas drásticas.',
    },
    styles: [
      'Estilo *hokidachi* — vassoura, escolha clássica.',
      'Estilo *sekijoju* — raiz-sobre-pedra, raízes vigorosas envolvendo a rocha.',
      'Estilo *yose-ue* — floresta, muito comum.',
    ],
    techniques: [
      {
        name: 'Aramação',
        period: 'Final do inverno (sem folhas) ou início do verão (brotos macios)',
        description:
          'Arame de alumínio. A casca é sensível — verifique com regularidade e retire em 6 a 8 semanas.',
      },
      {
        name: 'Repotagem',
        period: 'Primavera',
        description:
          'Encurte as raízes em um terço. Tolera tratamento mais agressivo que o A. palmatum.',
      },
      {
        name: 'Desfolha',
        period: 'Início do verão',
        description: 'A desfolha total favorece ramificação mais fina e folhas menores.',
      },
    ],
    propagation: {
      period: 'Estacas semilenhosas no início do verão',
      postCare:
        'Meia-sombra, mantidas úmidas. Enraizamento em 6 a 8 semanas. A semeadura na primavera, após estratificação a frio, também é bem-sucedida.',
    },
    photos: ['Bonsai de bordo-tridente', 'Casca de bordo-tridente', 'Folhas trilobadas'],
  },
  'larix-kaempferi': {
    popularName: 'Lariço-japonês',
    introduction:
      'Uma conífera incomum, que adquire tonalidade dourada no outono e perde as acículas. Cresce rápido e ramifica com finura — ideal para composições em floresta e para *yamadori* alpinos. Na primavera, a brotação verde-clara tem um frescor impressionante.',
    care: {
      sun: 'Sol pleno o ano todo.',
      soil: 'Akadama 50% + pumice 30% + lava 20%, levemente ácido.',
      watering:
        'Mantenha o substrato uniformemente úmido — o lariço gosta de mais água que as demais coníferas.',
      fertilizing:
        'A cada duas semanas durante o período de crescimento (primavera–outono); reduzido no pleno verão.',
      temperature: 'Muito rústico, até −25 °C; ao ar livre o ano todo.',
      pruning: 'Aparae os brotos novos na primavera, deixando 2 a 3 tufos de acículas.',
    },
    styles: [
      'Estilo *yose-ue* — floresta, as composições de lariço são icônicas (por exemplo, Walter Pall).',
      'Estilo *moyogi* — vertical informal.',
      'Estilo *bunjin* — literato, condiz com o porte natural junto à linha das árvores nas montanhas.',
    ],
    techniques: [
      {
        name: 'Aramação',
        period: 'Inverno, sem acículas',
        description:
          'Arame de alumínio ou cobre. A casca é sensível; na ascensão da seiva na primavera, proteja a casca dos ramos mais grossos antes de aramar.',
      },
      {
        name: 'Repotagem',
        period: 'Primavera, pouco antes da brotação',
        description: 'Encurte as raízes em um terço. Preserve a micorriza.',
      },
      {
        name: 'Pinçagem de acículas',
        period: 'Primavera, durante a brotação',
        description:
          'Pince com os dedos os brotos jovens e macios, deixando 2 a 3 tufos de acículas; favorece ramificação compacta.',
      },
    ],
    propagation: {
      period: 'Primavera, após estratificação a frio',
      postCare:
        'Estratifique as sementes a frio por 4 a 6 semanas. Germinação em 3 a 6 semanas. A coleta de *yamadori* nos Alpes, no final do inverno, é comum.',
    },
    photos: [
      'Bonsai de lariço no outono',
      'Brotação primaveril de Larix',
      'Lariço-japonês yamadori',
    ],
  },
  'chamaecyparis-obtusa': {
    popularName: 'Cipreste-hinoki',
    introduction:
      'Uma elegante conífera japonesa, de folhagem escamosa em forma de leque e porte naturalmente compacto. O cultivar "Nana Gracilis" é o mais apreciado no bonsai. Os brotos internos morrem com facilidade quando recebem pouca luz — o raleio regular é obrigatório.',
    care: {
      sun: 'Do sol pleno à meia-sombra; é essencial que a luz alcance o interior da copa.',
      soil: 'Akadama 50% + pumice 30% + lava 20%, levemente ácido.',
      watering: 'Mantenha o substrato uniformemente úmido — jamais deixe ressecar.',
      fertilizing:
        'A cada duas semanas durante o período de crescimento (primavera–outono), com adubo orgânico.',
      temperature: 'Rústico até −15 °C com proteção radicular; ao ar livre o ano todo.',
      pruning:
        'Pince os brotos escamosos com os dedos (não corte com tesoura — os cortes ficam marrons). Faça raleios com regularidade.',
    },
    styles: [
      'Estilo *chokkan* — vertical formal, evoca os hinokis dos templos.',
      'Estilo *moyogi* — vertical informal.',
      'Estilo *yose-ue* — floresta, muito expressivo.',
    ],
    techniques: [
      {
        name: 'Aramação',
        period: 'Final do verão ao outono',
        description:
          'Arame de cobre. A madeira é relativamente flexível; monitore com regularidade.',
      },
      {
        name: 'Repotagem',
        period: 'Primavera, antes da brotação',
        description: 'Poda de raízes conservadora (no máximo um terço). Preserve a micorriza.',
      },
      {
        name: 'Raleio',
        period: 'Final do verão ao outono',
        description:
          'Remova os brotos internos e sobrepostos para que a luz alcance o interior — evita a morte dos brotos internos.',
      },
    ],
    propagation: {
      period: 'Estacas semilenhosas no final do verão',
      postCare:
        'Em estufim frio, em meia-sombra, mantidas úmidas. Enraizamento em 6 a 12 meses. A enxertia é comum para cultivares selecionados.',
    },
    photos: ['Cipreste-hinoki', 'Folhagem escamosa do Nana Gracilis', 'Bonsai de Chamaecyparis'],
  },
  'fagus-sylvatica': {
    popularName: 'Faia-europeia',
    introduction:
      'Uma espécie caducifólia europeia, de casca lisa e cinza-prateada e folhagem cor de cobre que permanece marcescente no galho durante todo o inverno. Muito apreciada em composições em floresta e em árvores solitárias. Cresce devagar — mas, com o tempo, desenvolve um tronco lindamente sulcado e uma copa densa.',
    care: {
      sun: 'Meia-sombra — a faia não tolera o sol forte do meio-dia, sobretudo no verão.',
      soil: 'Akadama 50% + pumice 30% + lava 20%, levemente ácido.',
      watering:
        'Mantenha o substrato uniformemente úmido; no verão, com fartura, jamais deixando secar.',
      fertilizing: 'A cada duas semanas da primavera ao início do verão e no início do outono.',
      temperature: 'Muito rústica, até −20 °C; ao ar livre o ano todo.',
      pruning:
        'Poda principal no final do inverno, antes da brotação. UM único fluxo de crescimento por ano — portanto, sem podas repetidas como no bordo.',
    },
    styles: [
      'Estilo *chokkan* — vertical formal, segue o porte natural.',
      'Estilo *yose-ue* — floresta; bosques de faia estão entre as composições de bonsai mais belas.',
      'Estilo *moyogi* — vertical informal.',
    ],
    techniques: [
      {
        name: 'Aramação',
        period: 'Final do outono ao inverno',
        description:
          'Arame de alumínio. A casca é muito sensível — use fita protetora; no máximo 4 a 6 semanas.',
      },
      {
        name: 'Repotagem',
        period: 'Primavera, quando as gemas incham',
        description: 'Encurte as raízes em um terço com cuidado.',
      },
      {
        name: 'Seleção de gemas',
        period: 'Final do inverno',
        description:
          'Como a faia só brota uma vez por ano, remova de forma seletiva as gemas indesejadas para direcionar a energia aos brotos escolhidos.',
      },
    ],
    propagation: {
      period: 'Outono, logo após a maturação, ou primavera, após estratificação a frio',
      postCare:
        'Estratifique a frio por 3 meses. A germinação ocorre na primavera. As estacas são muito difíceis — a coleta de *yamadori* é uma alternativa popular.',
    },
    photos: [
      'Faia-europeia como bonsai',
      'Marcescência invernal da faia',
      'Composição em floresta de Fagus',
    ],
  },
  'chaenomeles-japonica': {
    popularName: 'Marmeleiro-do-japão',
    introduction:
      'Um bonsai florífero e armado de espinhos, com flores intensas em vermelho, rosa ou branco no início da primavera, frequentemente antes da brotação das folhas. Produz pequenos frutos perfumados, como marmelos. Tolera podas drásticas e florece com fartura, mas exige dormência invernal fria para uma boa floração.',
    care: {
      sun: 'Sol pleno o ano todo.',
      soil: 'Akadama 50% + pumice 30% + lava 20%.',
      watering: 'Mantenha o substrato uniformemente úmido, com fartura no verão.',
      fertilizing:
        'A cada duas semanas durante o período de crescimento (primavera–outono); no verão, adubo rico em potássio para induzir botões florais.',
      temperature:
        'Rústico até −20 °C; ao ar livre o ano todo, com período frio indispensável para a indução floral.',
      pruning: 'Pode logo após a floração — os botões se formam em madeira velha.',
    },
    styles: [
      'Estilo *moyogi* — vertical informal.',
      'Estilo *kabudachi* — multitroncos, porte natural.',
      'Estilo *han-kengai* — semicascata.',
    ],
    techniques: [
      {
        name: 'Aramação',
        period: 'Final do outono ao inverno',
        description:
          'Arame de alumínio. Atenção aos espinhos. Não arame muito justo — a casca é sensível.',
      },
      {
        name: 'Repotagem',
        period: 'Primavera, logo após a floração ou antes da brotação',
        description: 'Encurte as raízes em um terço.',
      },
      {
        name: 'Poda pós-floração',
        period: 'Logo após a floração',
        description:
          'Encurte os brotos floridos para 2 a 3 gemas. Nada de podas drásticas no verão — eliminariam as gemas florais.',
      },
    ],
    propagation: {
      period: 'Estacas semilenhosas no verão',
      postCare:
        'Meia-sombra, úmido, com inverno passado em estufim frio. Enraizamento em 8 a 12 semanas. Brotos de raiz também são viáveis.',
    },
    photos: [
      'Marmeleiro-do-japão com flores vermelhas',
      'Bonsai de Chaenomeles',
      'Fruto do marmeleiro',
    ],
  },
  'wisteria-sinensis': {
    popularName: 'Glicínia-chinesa',
    introduction:
      'Um espetacular bonsai florífero, com cachos pendentes de flores violetas ou brancas no final da primavera. Muito vigoroso e sedento — exige enormes quantidades de água no verão. Com a idade, o tronco desenvolve uma casca extraordinariamente sulcada e uma robustez retorcida impressionante.',
    care: {
      sun: 'Sol pleno o ano todo — indispensável para a floração.',
      soil: 'Akadama 50% + pumice 30% + lava 20%, com boa retenção de umidade.',
      watering:
        'Muito sedento — no verão, regue até duas vezes ao dia. Durante a floração, deixe o vaso eventualmente em uma bandeja com água.',
      fertilizing:
        'A cada duas semanas durante o período de crescimento (primavera–outono); no verão, adubo rico em fósforo e potássio.',
      temperature: 'Rústica até −20 °C; ao ar livre o ano todo.',
      pruning:
        'No verão, encurte os longos sarmentos para 4 a 6 gemas — induz a formação de gemas florais. Poda estrutural no inverno.',
    },
    styles: [
      'Estilo *kengai* — cascata, condiz com o porte naturalmente pendente das flores.',
      'Estilo *han-kengai* — semicascata, o mais comum.',
      'Estilo *moyogi* — vertical informal, com inflorescências pendentes.',
    ],
    techniques: [
      {
        name: 'Aramação',
        period: 'Primavera, depois da floração',
        description:
          'Arame de cobre para os ramos mais velhos, alumínio para os sarmentos jovens. A glicínia cresce muito rápido — verifique o arame com frequência.',
      },
      {
        name: 'Repotagem',
        period: 'Primavera, antes da brotação, ou logo após a floração',
        description:
          'Poda radicular agressiva (até a metade) é bem tolerada — a glicínia desenvolve enorme massa de raízes.',
      },
      {
        name: 'Poda de verão para favorecer floração',
        period: 'Pleno verão',
        description:
          'Encurte os longos sarmentos de verão para 4 a 6 gemas — força a planta a produzir botões florais em vez de massa foliar.',
      },
    ],
    propagation: {
      period: 'Primavera–início do verão',
      postCare:
        'A alporquia é muito bem-sucedida, com enraizamento em 6 a 12 semanas. A partir de sementes, são necessários de 7 a 15 anos até a primeira floração; plantas enxertadas são preferíveis.',
    },
    photos: [
      'Bonsai de glicínia em floração',
      'Cachos de glicínia',
      'Tronco retorcido de glicínia',
    ],
  },
  'prunus-mume': {
    popularName: 'Damasqueiro-japonês / Ume',
    introduction:
      'Símbolo do ano-novo japonês e do primeiro sinal da primavera — flores perfumadas rosadas, brancas ou vermelhas surgem no final do inverno, muitas vezes ainda na neve. Os exemplares mais antigos desenvolvem troncos caracteristicamente retorcidos e de modelagem dramática. Uma das espécies de bonsai mais carregadas de significado espiritual no Japão.',
    care: {
      sun: 'Sol pleno o ano todo — indispensável para uma floração abundante.',
      soil: 'Akadama 50% + pumice 30% + lava 20%.',
      watering: 'Mantenha o substrato uniformemente úmido, com fartura no verão.',
      fertilizing:
        'A cada duas semanas durante o período de crescimento (primavera–outono), com adubação forte logo após a floração; no verão, ênfase em potássio.',
      temperature:
        'Rústico até −15 °C com proteção radicular; período frio indispensável para a indução floral.',
      pruning:
        'Pode com firmeza logo após a floração — os botões florais se formam na madeira do ano anterior.',
    },
    styles: [
      'Estilo *bunjin* — literato, condiz com o porte retorcido e elegante dos Ume antigos.',
      'Estilo *moyogi* — vertical informal.',
      'Estilo *shari* — áreas de madeira morta, simbólicas da resiliência das árvores velhas.',
    ],
    techniques: [
      {
        name: 'Aramação',
        period: 'Final do outono ao inverno, sem folhas',
        description:
          'A madeira é dura e quebradiça — dobre devagar, em etapas. Use fita protetora.',
      },
      {
        name: 'Repotagem',
        period: 'Logo após a floração',
        description: 'Encurte as raízes em um terço. Sele os cortes com pasta cicatrizante.',
      },
      {
        name: 'Poda pós-floração',
        period: 'Logo após a floração',
        description:
          'Encurte com firmeza os brotos floridos para 2 a 3 gemas, estimulando as gemas florais do ano seguinte.',
      },
    ],
    propagation: {
      period: 'Primavera–início do verão',
      postCare:
        'A alporquia é muito confiável. As estacas são possíveis, mas trabalhosas. Os cultivares costumam ir enxertados.',
    },
    photos: [
      'Flores de Ume no final do inverno',
      'Bonsai de Prunus mume',
      'Tronco retorcido de Ume',
    ],
  },
  'olea-europaea': {
    popularName: 'Oliveira',
    introduction:
      'Uma das mais antigas plantas cultivadas do mundo, de folhagem verde-prateada e tronco naturalmente retorcido e oco com a idade. Muito apreciada como *yamadori* da Espanha, Itália e Grécia. Tolera a seca de forma excelente, mas em Berlim não é plenamente rústica — exige abrigo frio e sem geada no inverno.',
    care: {
      sun: 'Sol pleno o ano todo — o quanto for possível.',
      soil: 'Akadama 40% + pumice 40% + lava 20%, muito drenante.',
      watering:
        'Com parcimônia — só regue quando o substrato estiver visivelmente seco. Suporta bem a seca.',
      fertilizing:
        'A cada duas semanas durante o período de crescimento (primavera–outono), com adubo orgânico.',
      temperature:
        'Tolera por curtos períodos até cerca de −5 °C; em Berlim, invernar livre de geada (0–10 °C) e em local claro.',
      pruning:
        'Pode os brotos depois de lignificados, deixando 2 a 3 pares de folhas. Suporta podas muito severas — até em madeira velha.',
    },
    styles: [
      'Estilo *moyogi* — vertical informal, com tronco retorcido.',
      'Estilo *shari* — os troncos naturalmente ocos das oliveiras antigas são ideais.',
      'Estilo *bunjin* — literato, condiz com a silhueta elegante.',
    ],
    techniques: [
      {
        name: 'Aramação',
        period: 'Final da primavera ao verão, durante o crescimento ativo',
        description:
          'A madeira é dura, mas surpreendentemente flexível. Arame de cobre para os ramos principais, alumínio para os brotos finos.',
      },
      {
        name: 'Repotagem',
        period: 'Final da primavera, com temperaturas estáveis acima de 15 °C',
        description:
          'Encurte as raízes em um terço. A oliveira se recupera rapidamente em ambiente quente e ensolarado.',
      },
      {
        name: 'Desfolha',
        period: 'Início do verão',
        description:
          'A desfolha total favorece folhas menores e ramificação mais fina — possível a cada 2 ou 3 anos.',
      },
    ],
    propagation: {
      period: 'Primavera–verão',
      postCare:
        'Estacas semilenhosas enraízam em 8 a 12 semanas sob condições úmidas e em meia-sombra. A coleta de *yamadori* no Mediterrâneo é fonte comum.',
    },
    photos: [
      'Oliveira como bonsai',
      'Folhagem verde-prateada de oliveira',
      'Tronco oco de oliveira',
    ],
  },
};

export const PTBR_PRIVACY = `
<header>
  <h1 class="font-display text-4xl sm:text-5xl text-text italic">Política de privacidade</h1>
  <p class="mt-2 text-text-muted">Atualizada em: 26 de maio de 2026</p>
</header>

<section class="space-y-3">
  <h2 class="font-display text-2xl text-text">1. Controlador dos dados</h2>
  <p>Responsável nos termos do Regulamento Geral de Proteção de Dados da União Europeia (RGPD/DSGVO):</p>
  <p>
    {SITE.legal.legalEntity}<br />
    {SITE.address.street}, {SITE.address.postalCode} {SITE.address.city}<br />
    E-mail: <a href={\`mailto:\${SITE.legal.dataControllerEmail}\`} class="text-accent-deep underline">{SITE.legal.dataControllerEmail}</a><br />
    Telefone: {SITE.legal.dataControllerPhone}
  </p>
</section>

<section class="space-y-3">
  <h2 class="font-display text-2xl text-text">2. Coleta e armazenamento de dados pessoais</h2>
  <p>Ao visitar este site, são registradas automaticamente informações de natureza geral (arquivos de log do servidor). Trata-se de dados técnicos, como o navegador utilizado, o sistema operacional ou o momento do acesso. Essas informações são processadas por necessidade técnica, para que a página acessada possa ser exibida corretamente para você.</p>
  <p>A base legal é o art. 6.º, n.º 1, alínea f) do RGPD/DSGVO (interesse legítimo na exibição tecnicamente correta da página).</p>
</section>

<section class="space-y-3">
  <h2 class="font-display text-2xl text-text">3. Newsletter</h2>
  <p>Este site de demonstração <strong>não processa nenhum dado</strong> ao receber inscrições de newsletter. O formulário é um modelo não funcional. Em um ambiente real, utilizaríamos o procedimento de double opt-in, com e-mail de confirmação, e o envio seria feito por um provedor em conformidade com o RGPD/DSGVO (por exemplo, Brevo ou Mailjet — servidores na União Europeia).</p>
</section>

<section class="space-y-3">
  <h2 class="font-display text-2xl text-text">4. Cookies e rastreamento</h2>
  <p>Utilizamos cookies tecnicamente necessários (para registrar o estado do banner de cookies). Cookies de análise e scripts externos só são carregados após o seu consentimento explícito pelo banner de cookies. Você pode revogar o consentimento a qualquer momento apagando os cookies nas configurações do navegador.</p>
</section>

<section class="space-y-3">
  <h2 class="font-display text-2xl text-text">5. Serviços de terceiros utilizados</h2>
  <ul class="list-disc list-inside space-y-2 text-text-muted">
    {SITE.legal.processors.map((p) => (
      <li><strong class="text-text">{p.name}</strong> — {p.purpose} (localização: {p.location})</li>
    ))}
  </ul>
  <p class="text-sm pt-2">Com os subcontratantes mencionados existem contratos de processamento de dados nos termos do art. 28 do RGPD/DSGVO.</p>
</section>

<section class="space-y-3">
  <h2 class="font-display text-2xl text-text">6. Prazo de armazenamento</h2>
  <p>Armazenamos dados pessoais apenas pelo tempo necessário às respectivas finalidades ou quando prazos legais de retenção assim o exigem:</p>
  <ul class="list-disc list-inside space-y-1 text-text-muted">
    <li>Logs do servidor: 7 a 14 dias, com exclusão automática em seguida</li>
    <li>Preferências de cookies (armazenadas localmente no navegador): até 180 dias ou até serem excluídas por você</li>
    <li>Correspondência por e-mail: até a conclusão integral do seu pedido; prazos legais de retenção previstos no Código Comercial alemão (HGB) e no Código Tributário alemão (AO) podem exigir armazenamento mais longo (até 10 anos para questões relevantes do ponto de vista comercial)</li>
  </ul>
</section>

<section class="space-y-3">
  <h2 class="font-display text-2xl text-text">7. Segurança dos dados</h2>
  <p>Este site utiliza criptografia TLS (HTTPS) em toda a transmissão de dados. Empregamos as seguintes medidas técnicas de proteção:</p>
  <ul class="list-disc list-inside space-y-1 text-text-muted">
    <li>Strict-Transport-Security (HSTS) com preload</li>
    <li>Content-Security-Policy para impedir cross-site scripting</li>
    <li>X-Frame-Options e X-Content-Type-Options contra clickjacking e MIME sniffing</li>
    <li>Acesso às áreas administrativas exclusivamente por autenticação em múltiplas etapas</li>
  </ul>
  <p>Apesar dessas medidas, não é possível garantir uma transmissão de dados completamente segura pela internet.</p>
</section>

<section class="space-y-3">
  <h2 class="font-display text-2xl text-text">8. Seus direitos</h2>
  <p>Você tem os seguintes direitos:</p>
  <ul class="list-disc list-inside space-y-1 text-text-muted">
    <li>Direito de acesso (art. 15 do RGPD/DSGVO)</li>
    <li>Direito de retificação (art. 16 do RGPD/DSGVO)</li>
    <li>Direito ao apagamento (art. 17 do RGPD/DSGVO)</li>
    <li>Direito à limitação do tratamento (art. 18 do RGPD/DSGVO)</li>
    <li>Direito à portabilidade dos dados (art. 20 do RGPD/DSGVO)</li>
    <li>Direito de oposição (art. 21 do RGPD/DSGVO)</li>
    <li>Direito de reclamação junto à autoridade de controle (art. 77 do RGPD/DSGVO)</li>
  </ul>
  <p class="pt-2">Para exercer seus direitos, entre em contato com: <a href={\`mailto:\${SITE.legal.dataControllerEmail}\`} class="text-accent-deep underline">{SITE.legal.dataControllerEmail}</a></p>
</section>

<section class="space-y-3 text-text-muted text-sm">
  <h2 class="font-display text-xl text-text">9. Autoridade de controle</h2>
  <p>A autoridade de controle responsável por nós é a Encarregada Berlinense de Proteção de Dados e Liberdade de Informação (Berliner Beauftragte für Datenschutz und Informationsfreiheit), Friedrichstr. 219, 10969 Berlin.</p>
</section>
`;

export const PTBR_IMPRINT = `
<h1 class="font-display text-4xl sm:text-5xl text-text italic">Informações legais</h1>
<p class="mt-2 text-text-muted">Informações obrigatórias conforme § 5 da TMG (legislação alemã)</p>

<section class="mt-10 space-y-2">
  <h2 class="font-display text-2xl text-text">Prestador</h2>
  <p>{SITE.legal.legalEntity}</p>
  <p>{SITE.address.street}</p>
  <p>{SITE.address.postalCode} {SITE.address.city}</p>
  <p>Alemanha</p>
</section>

<section class="mt-8 space-y-2">
  <h2 class="font-display text-2xl text-text">Representado por</h2>
  <p>{SITE.legal.legalRepresentatives}</p>
</section>

<section class="mt-8 space-y-2">
  <h2 class="font-display text-2xl text-text">Contato</h2>
  <p>Telefone: <a href={\`tel:\${SITE.phone}\`} class="text-accent-deep underline">{SITE.phoneDisplay}</a></p>
  <p>E-mail: <a href={\`mailto:\${SITE.email}\`} class="text-accent-deep underline">{SITE.email}</a></p>
</section>

<section class="mt-8 space-y-2">
  <h2 class="font-display text-2xl text-text">Número de identificação fiscal (IVA)</h2>
  <p>Número de identificação para fins de IVA conforme § 27a da Lei alemã do IVA (Umsatzsteuergesetz): {SITE.legal.taxId}</p>
</section>

<section class="mt-8 space-y-2">
  <h2 class="font-display text-2xl text-text">Responsável pelo conteúdo nos termos do § 18, n.º 2, do MStV</h2>
  <p>{SITE.legal.legalRepresentatives}</p>
  <p>{SITE.address.street}, {SITE.address.postalCode} {SITE.address.city}</p>
</section>

<section class="mt-8 space-y-3 text-text-muted">
  <h2 class="font-display text-2xl text-text">Resolução de litígios</h2>
  <p>
    A Comissão Europeia disponibiliza uma plataforma para resolução extrajudicial de litígios (ODR): <a href="https://ec.europa.eu/consumers/odr" class="text-accent-deep underline" target="_blank" rel="noopener noreferrer">https://ec.europa.eu/consumers/odr</a>.
  </p>
  <p>Nosso e-mail está disponível acima, nesta página de informações legais.</p>
  <p>Não temos disponibilidade nem obrigação de participar de procedimentos de resolução de litígios perante uma entidade de arbitragem de consumo.</p>
</section>

<section class="mt-8 space-y-3 text-text-muted text-sm">
  <h2 class="font-display text-xl text-text">Aviso de responsabilidade</h2>
  <p>Os conteúdos deste site de demonstração foram elaborados para fins ilustrativos. Apesar do cuidado na elaboração, não assumimos responsabilidade pela exatidão, integridade ou atualidade das informações disponibilizadas. As orientações botânicas baseiam-se em práticas consagradas de bonsai, mas não substituem o aconselhamento técnico individualizado.</p>
</section>
`;
