/**
 * Build a responsive srcset for an agency hero/secondary photograph.
 * Expects 3 variants in /public/img/...: `name-768.webp` (mobile), `name-1280.webp`
 * (tablet), `name.webp` (desktop 1920w). Pre-generated by
 * `scripts/generate-srcset.mjs`.
 *
 * Use as: `<img src={src} srcset={heroSrcset(src)} sizes="100vw" />`.
 */
export function heroSrcset(src: string): string {
  if (!src.endsWith('.webp')) return src;
  const base = src.slice(0, -'.webp'.length);
  return `${base}-768.webp 768w, ${base}-1280.webp 1280w, ${src} 1920w`;
}
